import {supabase,siteURL,signOut} from './auth-client.js';
import {adminRequest} from './admin-client.js';
const $=selector=>document.querySelector(selector), content=$('#content'),dialog=$('#actionDialog');
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const number=value=>value===null||value===undefined?'—':Number(value).toLocaleString('en-AU');
const date=value=>value?new Intl.DateTimeFormat('en-AU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Never';
const labels={money:'Play money adjustment',xp:'House XP granted',stats:'Statistics updated','football-tokens':'Football tokens granted','airport-cash':'Airport cash granted','airport-research':'Research granted','airport-diamonds':'Diamonds granted',level:'Level updated',unlock:'Unlock updated',warn:'Warning issued',suspend:'Player suspended',lift:'Suspension lifted',ban:'Permanent ban','report-create':'Report created','report-resolve':'Report resolved',flag:'Activity flagged','flag-resolve':'Flag resolved','staff-role':'Staff role updated','revoke-access':'Panel access revoked'};
let actor=null,viewData=null,tab='overview',period='24h',filters={search:'',status:'all',kind:'all',offset:0},sequence=0,busy=false,noticeTimer,expiryTimer;
const isAdmin=()=>actor?.role==='admin';
const params=()=>{const parts=location.hash.slice(1).split('/');return {view:parts[0]||'dashboard',id:parts[1],section:parts[2]};};
const linkPlayer=id=>`#player/${encodeURIComponent(id)}`;
const status=value=>`<span class="status ${escape(value)}">${escape(value)}</span>`;
const button=(label,attributes='')=>`<button ${attributes}>${escape(label)}</button>`;
const heading=(title,subtitle,aside='')=>`<section class="heading"><div><h1>${escape(title)}</h1><p>${escape(subtitle)}</p></div>${aside}</section>`;
const footer=()=>`<footer class="footer"><span>Last updated ${escape(date(new Date()))}</span><span>Dorra House / ${escape(actor?.role||'Administration')}</span></footer>`;
function notify(message,error=false){clearTimeout(noticeTimer);const el=$('#notice');el.textContent=message;el.className=`notice ${error?'error':'success'}`;el.hidden=false;noticeTimer=setTimeout(()=>el.hidden=true,8000);}
function periodControl(){return `<div class="periods" aria-label="Time period">${[['24h','Last 24h'],['7d','7d'],['30d','30d'],...(params().view==='activity'&&params().id?[['all','All history']]:[])].map(([id,label])=>button(label,`data-period="${id}" aria-pressed="${period===id}"`)).join('')}</div>`;}
function empty(title,copy){return `<section class="empty"><h2>${escape(title)}</h2><p>${escape(copy)}</p></section>`;}
function table(headings,rows,widths=[]){return `<div class="table-wrap"><table><colgroup>${headings.map((_,i)=>`<col class="width-${widths[i]||20}">`).join('')}</colgroup><thead><tr>${headings.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function activityTable(rows,compact=false){if(!rows.length)return empty('No activity yet','Recorded staff actions will appear here.');return table(compact?['Time','Admin','Action','Player','Outcome']:['Time','Actor','Action','Player','Reason','Outcome'],rows.map(r=>`<tr><td class="time">${escape(compact?new Intl.DateTimeFormat('en-AU',{hour:'2-digit',minute:'2-digit',hourCycle:'h23',...(period==='24h'?{}:{day:'2-digit',month:'short'})}).format(new Date(r.createdAt)):date(r.createdAt))}</td><td>${escape(r.actor)}</td><td>${escape(labels[r.action]||r.action)}${r.changes?.length?(compact?` · ${escape(r.changes.map(c=>typeof c.before==='number'&&typeof c.after==='number'?`${formatDelta(c.before,c.after)} ${c.label.toLowerCase()}`:c.label+' '+formatValue(c.after)).join(' · '))}`:`<span class="reason">${escape(r.changes.map(c=>`${c.label}: ${formatValue(c.before)} → ${formatValue(c.after)}`).join(' · '))}</span>`):''}</td><td><a class="table-link" href="${linkPlayer(r.targetId)}">${escape(r.target)}</a></td>${compact?'':`<td>${escape(r.reason)}</td>`}<td>${status(r.outcome)}</td></tr>`),compact?[12,17,42,19,10]:[12,14,24,16,24,10]);}
function formatDelta(before,after){if(typeof before==='number'&&typeof after==='number'){const delta=after-before;return `${delta>0?'+':''}${number(delta)}`;}if(before&&after&&typeof before==='object'&&typeof after==='object')return Object.keys(after).filter(k=>typeof after[k]==='number'&&typeof before[k]==='number').map(k=>`${k} ${formatDelta(before[k],after[k])}`).join(' · ');return '—';}
function formatValue(value){return value===null?'None':typeof value==='object'?Object.entries(value).map(([k,v])=>`${k} ${number(v)}`).join(' · '):typeof value==='number'?number(value):String(value);}
function pager(data){return `<div class="pager"><small>Showing ${data.rows.length?data.offset+1:0}–${data.offset+data.rows.length} of ${number(data.total)}</small><div class="actions">${button('Previous',`data-page="-1" ${data.offset===0?'disabled':''}`)}${button('Next',`data-page="1" ${data.offset+data.rows.length>=data.total?'disabled':''}`)}</div></div>`;}
function toolbar(searchLabel,options,kind=false){return `<form id="filterForm" class="toolbar"><label>${escape(searchLabel)}<input name="search" maxlength="80" value="${escape(filters.search)}" placeholder="${escape(searchLabel)}"></label>${kind?`<label>Action<select name="kind">${[['all','All actions'],...Object.entries(labels)].map(([id,label])=>`<option value="${id}" ${filters.kind===id?'selected':''}>${escape(label)}</option>`).join('')}</select></label>`:`<label>Status<select name="status">${options.map(([id,label])=>`<option value="${id}" ${filters.status===id?'selected':''}>${escape(label)}</option>`).join('')}</select></label>`}${button('Apply filters','type="submit"')}${button('Clear filters','type="button" data-clear')}</form>`;}
function dashboard(data){return heading('Dashboard',new Intl.DateTimeFormat('en-AU',{dateStyle:'full'}).format(new Date())+' · '+Intl.DateTimeFormat().resolvedOptions().timeZone,periodControl())+`<section class="metrics" aria-label="Overview">${[['Active players',data.activePlayers,'Accepted commands in selected period','#players'],['Open reports',data.openReports,'Open staff-created reports','#reports'],['Flagged activity',data.flaggedActivity,'Unresolved manual flags','#players'],['Game changes',data.gameChanges,'Resource and progression updates','#activity']].map(([label,value,copy,url])=>`<a class="metric" href="${url}"><span>${label}</span><strong>${number(value)}</strong><small>${copy}</small></a>`).join('')}</section><section class="section-heading"><h2>Recent activity</h2><a class="button" href="#activity">View all activity</a></section>`+activityTable(data.activity.slice(0,8),true)+footer();}
function players(data,staff=false){return heading(staff?'Staff management':'Players',staff?'Approve staff roles and revoke temporary panel access.':'Find a player and manage their house record.')+toolbar('Search by username',[['all','All statuses'],['active','Active'],['suspended','Suspended'],['banned','Banned'],['disabled','Disabled']])+(!data.rows.length?empty(filters.search||filters.status!=='all'?'No matching players':'No players yet','Clear your filters or wait for players to create a House account.'):table(['Player','Player ID','Status','Level','Last active'],data.rows.map(p=>`<tr><td><a class="table-link" href="${linkPlayer(p.userId)}">${escape(p.username)}</a>${p.displayName?`<span class="reason">${escape(p.displayName)}</span>`:''}${staff?`<span class="reason">${p.owner?'Owner':escape(p.role)}</span>`:''}</td><td><small>${escape(p.userId)}</small></td><td>${status(p.status)}</td><td>${number(p.level)}</td><td>${escape(date(p.lastPlayedAt))}</td></tr>`),[29,18,15,12,26]))+pager(data)+footer();}
function profile(data){const p=data.player;const restricted=['resources','progression'].includes(tab)&&!isAdmin();if(restricted)return heading('Permission denied','Resource and progression controls require an administrator.')+`<a class="button" href="${linkPlayer(p.userId)}" data-overview>Back to overview</a>`;
  const actions=`<div class="actions"><a class="button" href="#players">Back to players</a><span class="push"></span>${button('Create report','data-action="report-create"')}${button('Warn player','data-action="warn" class="primary"')}${button('Suspend player',`data-action="suspend" ${p.owner?'disabled':''}`)}${isAdmin()?`${p.status==='suspended'?button('Lift suspension','data-action="lift"'):''}${button('Permanently ban',`data-action="ban" class="danger" ${p.owner||p.banned?'disabled':''}`)}`:''}</div>`;
  const tabs=`<div class="tabs" aria-label="Player sections">${['overview',...(isAdmin()?['resources','progression']:[]),'history'].map(name=>button(name[0].toUpperCase()+name.slice(1),`data-tab="${name}" aria-pressed="${tab===name}"`)).join('')}</div>`;
  let body='';
  if(tab==='resources')body=resources(p);
  else if(tab==='progression')body=progression(data);
  else if(tab==='history')body=`<section class="section-heading"><h2>Player history</h2><a class="button" href="#activity/${p.userId}">View all recorded history</a></section>`+activityTable(data.history);
  else body=`<h2>House record</h2><dl class="record">${[['Level',number(p.level)],['Rounds',number(p.rounds)],['Wins',number(p.wins)],['Current balance',isAdmin()?number(p.resources.money):'Administrator access required']].map(([label,value])=>`<div><dt>${label}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl><h2>Account context</h2><dl class="record"><div><dt>Role</dt><dd>${escape(p.owner?'Owner':p.role)}</dd></div><div><dt>House XP</dt><dd>${number(p.xp)}</dd></div><div><dt>Suspended until</dt><dd>${escape(p.status==='suspended'?date(p.suspendedUntil):'None')}</dd></div><div><dt>Cloud save</dt><dd>${p.hasSave?'Available':'Not created yet'}</dd></div></dl><section class="section-heading"><h2>Moderation history</h2>${button('View history','data-tab="history"')}</section>`+activityTable(data.history.filter(r=>['warn','suspend','lift','ban'].includes(r.action)))+`<section class="section-heading"><h2>Activity flags</h2>${button('Flag activity','data-action="flag"')}</section>`+(data.flags.length?`<div class="flag-list">${data.flags.map(f=>`<div><p>${escape(f.reason)}<span class="reason">${escape(date(f.createdAt))}</span></p>${button('Resolve flag',`data-action="flag-resolve" data-flag="${f.id}"`)}</div>`).join('')}</div>`:empty('No unresolved flags','Flags are recorded manually by staff.'));
  if(actor.owner&&tab==='overview')body+=`<h2>Staff access</h2><div class="actions">${button('Change staff role',`data-action="staff-role" ${p.owner?'disabled':''}`)}${button('Revoke panel access','data-action="revoke-access"')}</div>`;
  return heading(p.username,`${p.userId} · Joined ${date(p.createdAt)} · Last active ${date(p.lastPlayedAt)}`,status(p.status))+actions+tabs+body+footer();
}
function control(title,value,copy,action,disabled=false){return `<article class="control-card"><h3>${escape(title)}</h3><strong class="balance">${number(value)}</strong><p>${escape(copy)}</p>${button('Adjust '+title.toLowerCase(),`data-action="${action}" ${disabled?'disabled':''}`)}</article>`;}
function resources(p){if(!p.hasSave)return empty('No cloud save','This player must enter the House before resources can be adjusted.');const r=p.resources;return `<h2>House & club resources</h2><div class="form-grid">${control('Play money',r.money,'Add an exact amount or remove up to the current balance.','money')}${control('House XP',p.xp,'XP advances levels using the game’s existing progression rules.','xp')}${control('Player statistics',p.rounds,`${number(p.wins)} wins. Wins cannot exceed rounds.`,'stats')}${control('Football tokens',r.footballTokens,r.footballClub?'Existing club token balance.':'Create a football club first.','football-tokens',!r.footballClub)}</div><h2>Airport resources</h2>${r.airportCareer?`<div class="form-grid">${control('Diamonds',r.diamonds,'Shared across the player’s existing airport career.','airport-diamonds')}${r.airports.map(a=>`<article class="control-card"><h3>${escape(a.id)}</h3><p>${number(a.cash)} cash · ${number(a.research)} research</p><div class="actions">${button('Add cash',`data-action="airport-cash" data-airport="${escape(a.id)}"`)}${button('Add research',`data-action="airport-research" data-airport="${escape(a.id)}"`)}</div></article>`).join('')}</div>`:empty('Airport career unavailable','The player must open Airport Sim before airport resources can be edited.')}`;}
function progression(data){const p=data.player;if(!p.hasSave)return empty('No cloud save','This player must enter the House first.');return `<h2>Progression & unlocks</h2><div class="form-grid">${control('House level',p.level,'Levels 1–99. Higher levels unlock the existing game floors.','level')}<article class="control-card"><h3>Boutique unlocks</h3><p>Grant or revoke eligible items. Level prerequisites still apply.</p>${button('Edit unlock','data-action="unlock"')}</article></div><h2>Current unlocks</h2><p class="muted">${escape((p.resources.owned||[]).map(id=>data.unlockCatalog.find(i=>i.id===id)?.name||id).join(' · ')||'No boutique items unlocked.')}</p>`;}
function reports(data){return heading('Reports','Review staff reports and record a clear resolution.')+toolbar('Search reports or players',[['all','All reports'],['open','Open'],['resolved','Resolved'],['dismissed','Dismissed']])+(!data.rows.length?empty(filters.search||filters.status!=='all'?'No matching reports':'No reports yet','Create a report from a player’s profile to record evidence and context.'):table(['Report','Player','Title','Status','Received'],data.rows.map(r=>`<tr><td><a class="table-link" href="#report/${r.id}">${escape(r.id.slice(0,8))}</a></td><td><a href="${linkPlayer(r.target)}">${escape(r.username)}</a></td><td>${escape(r.title)}</td><td>${status(r.status)}</td><td>${escape(date(r.created_at))}</td></tr>`),[16,19,30,15,20]))+pager(data)+footer();}
function report(data){const r=data.report;return heading(r.title,`Report ${r.id} · Created ${date(r.created_at)}`,status(r.status))+`<div class="actions"><a class="button" href="#reports">Back to reports</a><a class="button" href="${linkPlayer(r.target)}">Open player profile</a>${r.status==='open'?button('Resolve report','data-action="report-resolve" class="primary"'):''}</div><h2>Evidence</h2><div class="evidence">${escape(r.evidence)}</div><h2>Player context</h2><dl class="record"><div><dt>Player</dt><dd>${escape(r.username)}</dd></div><div><dt>Account</dt><dd>${status(data.player.status)}</dd></div><div><dt>Level</dt><dd>${number(data.player.level)}</dd></div><div><dt>Reported by</dt><dd>${escape(r.actorName)}</dd></div></dl>${r.resolution_reason?`<h2>Resolution</h2><p class="evidence">${escape(r.resolution_reason)}</p>`:''}<h2>Previous actions</h2>`+activityTable(data.history)+footer();}
function activity(data){return heading('Activity','A record of who changed what, why, and when.',periodControl())+toolbar('Search actions, reasons or players',[],true)+activityTable(data.rows)+pager(data)+footer();}
function clearSensitive(){sequence++;viewData=null;content.removeAttribute('aria-busy');dialog.close();$('#dialogContent').innerHTML='';$('#accountMenu').hidden=true;$('#accountButton').setAttribute('aria-expanded','false');}
function unlockScreen(message='Enter the staff access code to unlock this account for 30 minutes.'){clearInterval(expiryTimer);clearSensitive();content.innerHTML=`<section class="auth-card"><div><h1>Staff access</h1><p>${escape(message)}</p></div><p>Signed in as ${escape(actor?.username||'staff')} · ${escape(actor?.role||'')}</p><form id="unlockForm"><label>Access code<input id="accessCode" type="password" maxlength="46" required autocomplete="off" spellcheck="false" placeholder="Paste your access code"></label><p id="unlockError" class="form-error" role="alert"></p>${button('Unlock panel','class="primary" type="submit"')}</form><a href="index.html">Return to the House</a></section>`;$('#accessClock').textContent='Panel locked';$('#unlockForm').onsubmit=async event=>{event.preventDefault();const input=$('#accessCode'),code=input.value.trim();input.value='';const submit=event.submitter;submit.disabled=true;try{actor=await adminRequest('unlock',{code});setupActor();await load();}catch(error){$('#unlockError').textContent=error.message;}finally{if(submit.isConnected)submit.disabled=false;}};}
function accessError(error){clearInterval(expiryTimer);if(actor)actor.unlocked=false;clearSensitive();if(['UNAUTHORIZED','AUTH_SESSION_ENDED'].includes(error.code)){content.innerHTML=heading('Session ended','Sign in again to access administration.')+`<a class="button primary" href="${siteURL('login.html?next=admin.html')}">Sign in</a>`;actor=null;}else if(error.code==='ACCESS_EXPIRED'){if(actor)actor.unlocked=false;unlockScreen(error.message);}else if(['STAFF_REQUIRED','ACCOUNT_DISABLED','PERMISSION_DENIED'].includes(error.code)){content.innerHTML=heading('Permission denied',error.message)+`<a class="button" href="index.html">Return to the House</a>`;}else{content.innerHTML=empty('Unable to load the panel',error.message)+button('Retry','data-retry');}$('#accessClock').textContent='Panel locked';}
function setupActor(){if(!actor)return;$('#accountButton').textContent=actor.role==='admin'?'Admin':'Moderator';$('#accountName').textContent=actor.username;$('#staffLink').hidden=!actor.owner;clearInterval(expiryTimer);expiryTimer=setInterval(()=>{if(!actor?.expiresAt)return;const seconds=Math.max(0,Math.ceil((new Date(actor.expiresAt)-Date.now())/1000));$('#accessClock').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} remaining`;if(!seconds){clearInterval(expiryTimer);actor.unlocked=false;unlockScreen('Your 30-minute panel session has ended. Enter the code to continue.');}},1000);}
async function load(){if(!actor?.unlocked)return unlockScreen();const ticket=++sequence,{view,id,section}=params();if(view==='player'&&section)tab=section;if(!['dashboard','players','player','reports','report','activity','staff'].includes(view)){location.hash='dashboard';return;}
  if(view==='staff'&&!actor.owner)return accessError(Object.assign(new Error('Staff management is restricted to the House owner.'),{code:'PERMISSION_DENIED'}));
  content.setAttribute('aria-busy','true');content.innerHTML=empty('Loading','Fetching the latest House records.');document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+(view==='player'?'players':view==='report'?'reports':view)?'page':'false'));
  try{const args={...filters,period};if(view==='player')args.targetId=id;if(view==='report')args.reportId=id;if(view==='activity'&&id)args.targetId=id;
    const data=await adminRequest(view,args);if(ticket!==sequence)return;viewData=data;content.innerHTML=({dashboard,players,player:profile,reports,report,activity,staff:data=>players(data,true)})[view](data);bindFilters();
  }catch(error){if(ticket===sequence)accessError(error);}finally{if(ticket===sequence)content.removeAttribute('aria-busy');}
}
function bindFilters(){const form=$('#filterForm');if(form)form.onsubmit=event=>{event.preventDefault();const data=new FormData(form);filters={...filters,...Object.fromEntries(data),offset:0};void load();};}
function field(label,name,type='number',attributes=''){return `<label>${escape(label)}<input name="${name}" type="${type}" ${attributes} required></label>`;}
function select(label,name,options){return `<label>${escape(label)}<select name="${name}">${options.map(([value,text])=>`<option value="${escape(value)}">${escape(text)}</option>`).join('')}</select></label>`;}
function openAction(action,source){const p=viewData.player||viewData.player?.player||viewData.report;const targetId=viewData.report?.target||p.userId,username=viewData.report?.username||p.username;let fields='';
  if(['money','xp','football-tokens','airport-cash','airport-research','airport-diamonds'].includes(action))fields+=field('Amount','amount','number','min="1" step="1"');
  if(action==='money')fields+=select('Operation','direction',[['add','Add exact amount'],['remove','Remove, down to zero']]);
  if(action==='stats')fields+=`<div class="inline-fields">${field('Rounds','sessions','number',`min="0" max="1000000" step="1" value="${p.rounds}"`)}${field('Wins','wins','number',`min="0" max="1000000" step="1" value="${p.wins}"`)}</div>`;
  if(action==='level')fields+=field('House level','level','number',`min="1" max="99" value="${p.level}"`);
  if(action==='unlock')fields+=select('Item','unlockId',viewData.unlockCatalog.map(i=>[i.id,`${i.name} · Level ${i.level}`]))+select('Change','enabled',[['true','Grant unlock'],['false','Revoke unlock']]);
  if(action==='suspend')fields+=select('Suspension duration','duration',[[24,'24 hours'],[168,'7 days'],[720,'30 days']]);
  if(action==='ban')fields+=field(`Type ${username} to confirm`,'confirmation','text','autocomplete="off" maxlength="24"');
  if(action==='report-create')fields+=field('Report title','title','text','maxlength="120"')+'<label>Evidence<textarea name="evidence" maxlength="4000" required placeholder="Record the observed behavior and relevant context."></textarea></label>';
  if(action==='report-resolve')fields+=select('Resolution','resolution',[['resolved','Resolved'],['dismissed','Dismissed']]);
  if(action==='staff-role')fields+=select('Staff role','role',[['player','Player — remove staff permissions'],['moderator','Moderator'],['admin','Administrator']]);
  $('#dialogContent').innerHTML=`<h2 id="dialogTitle">${escape(labels[action])}</h2><p class="muted">${escape(username)}</p><form id="actionForm">${fields}<label>Reason<textarea name="reason" maxlength="1000" required placeholder="Explain why this change is needed."></textarea></label><p id="dialogError" class="form-error" role="alert"></p><div class="dialog-actions">${button('Cancel','type="button" data-close')}${button('Preview change','type="submit" class="primary"')}</div></form>`;dialog.showModal();
  $('#actionForm').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const submit=event.submitter;submit.disabled=true;const args={targetId,action,...Object.fromEntries(new FormData(event.target))};for(const key of ['amount','sessions','wins','level','duration'])if(args[key]!==undefined)args[key]=Number(args[key]);if(args.enabled!==undefined)args.enabled=args.enabled==='true';if(source.dataset.airport)args.airportId=source.dataset.airport;if(source.dataset.flag)args.flagId=source.dataset.flag;if(action==='report-resolve')args.reportId=viewData.report.id;
    const actionSequence=sequence;try{const preview=await adminRequest('preview',args);if(actor?.unlocked&&actionSequence===sequence&&dialog.open)showPreview(preview,action);}catch(error){if(actionSequence!==sequence)return;if(['ACCESS_EXPIRED','STAFF_REQUIRED','AUTH_SESSION_ENDED'].includes(error.code))accessError(error);else $('#dialogError').textContent=error.message;}finally{busy=false;if(submit.isConnected)submit.disabled=false;}};
}
function showPreview(preview,action){const requestId=crypto.randomUUID(),confirmationSequence=sequence;$('#dialogContent').innerHTML=`<h2 id="dialogTitle">Confirm ${escape(labels[action].toLowerCase())}</h2><p class="muted">${escape(preview.target)} · Preview expires ${escape(date(preview.expiresAt))}</p><div><div class="preview-change"><small>CHANGE</small><small>BEFORE</small><small>AFTER</small><small>DELTA</small></div>${preview.changes.map(c=>`<div class="preview-change"><strong>${escape(c.label)}</strong><span>${escape(formatValue(c.before))}</span><span>${escape(formatValue(c.after))}</span><span>${escape(formatDelta(c.before,c.after))}</span></div>`).join('')}</div><div><h3>Reason</h3><p class="preview-reason">${escape(preview.reason)}</p></div><p id="dialogError" class="form-error" role="alert"></p><div class="dialog-actions">${button('Cancel','data-close')}${button('Confirm change',`id="confirmChange" class="${action==='ban'?'danger':'primary'}"`)}</div>`;
  $('#confirmChange').onclick=async event=>{if(busy)return;busy=true;event.target.disabled=true;try{await adminRequest('commit',{}, {previewId:preview.id,requestId});if(confirmationSequence!==sequence)return;dialog.close();notify('Change saved and recorded in activity.');await load();}catch(error){if(confirmationSequence!==sequence)return;if(['ACCESS_EXPIRED','STAFF_REQUIRED','AUTH_SESSION_ENDED'].includes(error.code))accessError(error);else{$('#dialogError').textContent=error.message;if(['STALE_REVISION','PREVIEW_EXPIRED'].includes(error.code)){$('#confirmChange').hidden=true;$('#dialogError').insertAdjacentHTML('afterend',button('Refresh player','data-refresh-player'));}else event.target.textContent='Retry confirmation';}}finally{busy=false;if(event.target.isConnected)event.target.disabled=false;}};
}
document.addEventListener('click',event=>{const buttonEl=event.target.closest('button');if(!buttonEl||buttonEl.disabled)return;
  if(buttonEl.hasAttribute('data-close'))dialog.close();
  if(buttonEl.hasAttribute('data-retry'))void initialize();
  if(buttonEl.hasAttribute('data-refresh-player')){dialog.close();void load();}
  if(buttonEl.dataset.period){period=buttonEl.dataset.period;filters.offset=0;void load();}
  if(buttonEl.dataset.page){filters.offset=Math.max(0,filters.offset+Number(buttonEl.dataset.page)*40);void load();}
  if(buttonEl.hasAttribute('data-clear')){filters={search:'',status:'all',kind:'all',offset:0};void load();}
  if(buttonEl.dataset.tab){tab=buttonEl.dataset.tab;content.innerHTML=profile(viewData);}
  if(buttonEl.dataset.action)openAction(buttonEl.dataset.action,buttonEl);
});
$('.skip-link').onclick=event=>{event.preventDefault();content.focus();};
$('#accountButton').onclick=()=>{const menu=$('#accountMenu');menu.hidden=!menu.hidden;$('#accountButton').setAttribute('aria-expanded',String(!menu.hidden));};
$('#lockButton').onclick=async()=>{try{await adminRequest('lock');actor.unlocked=false;unlockScreen();}catch(error){accessError(error);}};
$('#signOutButton').onclick=async()=>{try{if(actor)await adminRequest('lock');await signOut();}catch(error){notify(error.message,true);}};
window.addEventListener('hashchange',()=>{tab='overview';if(params().view==='activity'&&params().id)period='all';else if(period==='all')period='24h';filters={search:'',status:'all',kind:'all',offset:0};void load();});
supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){actor=null;accessError(Object.assign(new Error('Sign in again to continue.'),{code:'AUTH_SESSION_ENDED'}));}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&actor?.unlocked)void initialize();});
// Recheck server authority without extending the fixed grant or disrupting an
// in-progress form. Revocation clears every cached record and open dialog.
setInterval(async()=>{if(document.hidden||!actor?.unlocked)return;try{const current=await adminRequest('status');if(!current.unlocked){actor=current;unlockScreen('Panel access expired or was revoked. Enter the code to continue.');}else if(current.role!==actor.role||current.owner!==actor.owner){actor=current;setupActor();await load();}}catch(error){accessError(error);}},30000);
async function initialize(){if(params().view==='activity'&&params().id)period='all';try{actor=await adminRequest('status');setupActor();if(actor.unlocked)await load();else unlockScreen();}catch(error){accessError(error);}}
await initialize();
