import { supabase, siteURL } from './auth-client.js';
const $=selector=>document.querySelector(selector);
let mode='signin',busy=false;
function destination(){const next=new URLSearchParams(location.search).get('next');return siteURL(['index.html','football-manager.html','war-simulation.html','idle-airport.html'].includes(next)?next:'index.html');}
function message(text,error=false){const el=$('#accountMessage');el.textContent=text;el.hidden=!text;el.classList.toggle('error',error);}
function setMode(next){mode=next;message('');const signup=next==='signup',recovery=next==='recovery',reset=next==='reset';$('#usernameField').hidden=!signup;$('#username').required=signup;$('#username').disabled=!signup;$('#repeatField').hidden=!(signup||reset);$('#repeatPassword').required=signup||reset;$('#repeatPassword').disabled=!(signup||reset);$('#emailField').hidden=reset;$('#email').required=!reset;$('#email').disabled=reset;$('#passwordField').hidden=recovery;$('#password').required=!recovery;$('#password').disabled=recovery;$('#password').autocomplete=signup||reset?'new-password':'current-password';$('#signInTab').setAttribute('aria-pressed',String(next==='signin'));$('#signUpTab').setAttribute('aria-pressed',String(signup));$('.account-tabs').hidden=recovery||reset;$('#forgotPassword').hidden=next!=='signin';$('#backToSignIn').hidden=!(recovery||reset);$('#resendConfirmation').hidden=true;$('#formTitle').textContent=signup?'Make yourself at home.':recovery?'Reset your password.':reset?'Choose a new password.':'Welcome back.';$('#formCopy').textContent=signup?'Create your account and begin your House journey.':recovery?'We’ll send you a link if this email has an account.':reset?'Enter a new password for your Dorra House account.':'Sign in to continue your Dorra House journey.';$('#submitAccount').textContent=signup?'Create account':recovery?'Send reset link':reset?'Save password':'Sign in';}
$('#signInTab').onclick=()=>setMode('signin');$('#signUpTab').onclick=()=>setMode('signup');$('#forgotPassword').onclick=()=>setMode('recovery');$('#backToSignIn').onclick=()=>setMode('signin');
$('#showPassword').onclick=()=>{const show=$('#password').type==='password';$('#password').type=show?'text':'password';$('#showPassword').textContent=show?'Hide':'Show';$('#showPassword').setAttribute('aria-label',show?'Hide password':'Show password');$('#showPassword').setAttribute('aria-pressed',String(show));};
$('#accountForm').onsubmit=async event=>{event.preventDefault();if(busy)return;if((mode==='signup'||mode==='reset')&&$('#password').value!==$('#repeatPassword').value){message('The passwords don’t match.',true);return;}busy=true;$('#submitAccount').disabled=true;message('');try{const email=$('#email').value.trim(),password=$('#password').value;let response;
  if(mode==='signup'){response=await supabase.auth.signUp({email,password,options:{data:{username:$('#username').value.trim()},emailRedirectTo:siteURL('login.html').href}});if(response.error)throw response.error;if(response.data.session){location.replace(destination());return;}message('Your account was created. Confirm your email to sign in. If email confirmation is disabled in Supabase, you can sign in immediately.');$('#resendConfirmation').hidden=false;}
  else if(mode==='recovery'){response=await supabase.auth.resetPasswordForEmail(email,{redirectTo:siteURL('login.html?recovery=1').href});if(response.error)throw response.error;message('If an account exists, a password reset link has been requested.');}
  else if(mode==='reset'){response=await supabase.auth.updateUser({password});if(response.error)throw response.error;await supabase.auth.signOut();setMode('signin');message('Password updated. Sign in with your new password.');}
  else{response=await supabase.auth.signInWithPassword({email,password});if(response.error)throw response.error;location.replace(destination());}
}catch(error){let text=error.message||'We couldn’t complete that request. Try again.';if(/database error saving new user/i.test(text))text='That username may already be taken. Choose another username and try again.';if(/email not confirmed/i.test(text))$('#resendConfirmation').hidden=false;if(/email.*rate|smtp|sending confirmation|email address.*authorized/i.test(text))text='Email delivery is unavailable. Please contact the House owner to review the Supabase email settings.';message(text,true);}finally{busy=false;$('#submitAccount').disabled=false;}};
$('#resendConfirmation').onclick=async()=>{if(busy)return;busy=true;try{const {error}=await supabase.auth.resend({type:'signup',email:$('#email').value.trim(),options:{emailRedirectTo:siteURL('login.html').href}});if(error)throw error;message('A new confirmation email has been requested.');}catch(error){message(error.message,true);}finally{busy=false;}};
supabase.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')setMode('reset');});
const query=new URLSearchParams(location.search),hash=new URLSearchParams(location.hash.slice(1));
if(query.get('recovery')==='1'||hash.get('type')==='recovery')setMode('reset');
else{setMode('signin');const {data:{session}}=await supabase.auth.getSession();if(session)location.replace(destination());}
