import {MAX_BALANCE,MAX_PROTECTED_PROGRESS_BYTES} from './game-limits.js';
import {createAirportBridge} from './airport/vault-bridge.mjs';

// Dorra Vault v4: offline integrity worker. The signing key and authoritative
// snapshot stay outside the page's ordinary JavaScript execution context.
const DB_NAME='dorra-vault-v4',STORE='vault',KEY_ID='signing-key',PRIMARY_ID='primary',MAX_LEDGER=120,AUTHORITY_LOCK='dorra-vault-v4-authority';
const encoder=new TextEncoder();
const nativeSubtle=globalThis.crypto?.subtle;
const subtleSign=nativeSubtle?.sign.bind(nativeSubtle),subtleVerify=nativeSubtle?.verify.bind(nativeSubtle),importKey=nativeSubtle?.importKey.bind(nativeSubtle);
function requireSecurePrimitives(){if(!nativeSubtle||!subtleSign||!subtleVerify||!importKey||!globalThis.crypto?.getRandomValues)throw new Error('Secure WebCrypto is required for protected offline saves')}
const isVerificationKey=value=>!!nativeSubtle&&typeof CryptoKey!=='undefined'&&value instanceof CryptoKey&&value.type==='secret'&&!value.extractable&&value.usages.includes('verify');
const isVerifyOnlyKey=value=>isVerificationKey(value)&&value.usages.length===1;
async function createSigningPair(){requireSecurePrimitives();let raw=new Uint8Array(32);crypto.getRandomValues(raw);try{let algorithm={name:'HMAC',hash:'SHA-256'},signingKey=await importKey('raw',raw,algorithm,false,['sign']),verificationKey=await importKey('raw',raw,algorithm,false,['verify']);return {signingKey,verificationKey}}finally{raw.fill(0)}}
async function signMac(signingKey,message){return new Uint8Array(await subtleSign('HMAC',signingKey,message))}
async function verifyMac(verificationKey,signature,message){return subtleVerify('HMAC',verificationKey,signature,message)}

function openVault(){return new Promise((resolve,reject)=>{let request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function dbGet(db,id){return new Promise((resolve,reject)=>{let request=db.transaction(STORE).objectStore(STORE).get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function dbPut(db,id,value){return new Promise((resolve,reject)=>{let transaction=db.transaction(STORE,'readwrite');transaction.objectStore(STORE).put(value,id);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)})}
function dbPutPair(db,firstId,firstValue,secondId,secondValue){return new Promise((resolve,reject)=>{let transaction=db.transaction(STORE,'readwrite'),store=transaction.objectStore(STORE);store.put(firstValue,firstId);store.put(secondValue,secondId);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)})}
const bytesToBase64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes)));
const base64ToBytes=value=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));
const stablePayload=value=>JSON.stringify(value);
let db,key,currentEnvelope,currentSnapshot;

function macInput(revision,payload){return encoder.encode(`dorra-vault-v4\0${revision}\0${payload}`)}
async function verifyEnvelope(value){try{let envelope=typeof value==='string'?JSON.parse(value):value;if(envelope?.v!==4||!Number.isSafeInteger(envelope.r)||envelope.r<1||typeof envelope.p!=='string'||typeof envelope.m!=='string')return null;let valid=await verifyMac(key,base64ToBytes(envelope.m),macInput(envelope.r,envelope.p));if(!valid)return null;let snapshot=JSON.parse(envelope.p);return validateSnapshot(snapshot,true)?{envelope,snapshot}:null}catch{return null}}
async function seal(snapshot,revision,signingKey){let payload=stablePayload(snapshot),mac=await signMac(signingKey,macInput(revision,payload));return {v:4,r:revision,p:payload,m:bytesToBase64(mac)}}
function plainObject(value){return value&&typeof value==='object'&&!Array.isArray(value)}
function validLedger(snapshot){if(!Number.isSafeInteger(snapshot.ledgerBase)||snapshot.ledgerBase<0||!Array.isArray(snapshot.ledger)||snapshot.ledger.length>MAX_LEDGER)return false;let balance=snapshot.ledgerBase;for(let entry of snapshot.ledger){if(!plainObject(entry)||!Number.isSafeInteger(entry.delta)||!Number.isSafeInteger(entry.balance)||typeof entry.reason!=='string'||entry.reason.length>32||!Number.isSafeInteger(entry.at))return false;balance+=entry.delta;if(balance!==entry.balance||balance<0||balance>MAX_BALANCE)return false}return balance===snapshot.balance}
function validateSnapshot(snapshot,withLedger=false){if(!plainObject(snapshot)||!Number.isSafeInteger(snapshot.balance)||snapshot.balance<0||snapshot.balance>MAX_BALANCE||!Array.isArray(snapshot.history)||snapshot.history.length>8||!plainObject(snapshot.stats)||!plainObject(snapshot.progress))return false;let sessions=snapshot.stats.sessions,wins=snapshot.stats.wins;if(!Number.isSafeInteger(sessions)||sessions<0||sessions>1e7||!Number.isSafeInteger(wins)||wins<0||wins>sessions||!plainObject(snapshot.stats.games))return false;let level=snapshot.progress.level,xp=snapshot.progress.xp;if(!Number.isSafeInteger(level)||level<1||level>99||!Number.isSafeInteger(xp)||xp<0||xp>1e9||!Array.isArray(snapshot.progress.owned)||snapshot.progress.owned.length>1000||!plainObject(snapshot.progress.equipped)||!plainObject(snapshot.progress.configurations)||!plainObject(snapshot.progress.vehicles)||encoder.encode(stablePayload(snapshot.progress)).byteLength>MAX_PROTECTED_PROGRESS_BYTES)return false;return !withLedger||validLedger(snapshot)}
function freshSnapshot(input={}){let balance=Number.isSafeInteger(input.balance)&&input.balance>=0?Math.min(input.balance,MAX_BALANCE):1000,progress=plainObject(input.progress)?input.progress:{level:1,xp:0,owned:[],equipped:{},configurations:{},vehicles:{}};progress.vehicles=plainObject(progress.vehicles)?progress.vehicles:{};return {...input,balance,history:Array.isArray(input.history)?input.history.slice(0,8):[],stats:plainObject(input.stats)?input.stats:{sessions:0,wins:0,games:{}},progress,ledgerBase:balance,ledger:[]}}
function appendLedger(previous,next,reason){let ledgerBase=previous?.ledgerBase??next.balance,ledger=Array.isArray(previous?.ledger)?previous.ledger.slice():[],oldBalance=previous?.balance??next.balance,delta=next.balance-oldBalance;if(delta){ledger.push({delta,balance:next.balance,reason:String(reason||'game').slice(0,32),at:Date.now()});while(ledger.length>MAX_LEDGER){let removed=ledger.shift();ledgerBase=removed.balance}}return {...next,ledgerBase,ledger}}
async function installSnapshot(snapshot,revision){let pair=await createSigningPair(),envelope=await seal(snapshot,revision,pair.signingKey);await dbPutPair(db,KEY_ID,pair.verificationKey,PRIMARY_ID,envelope);key=pair.verificationKey;currentEnvelope=envelope;currentSnapshot=snapshot;return envelope}
async function loadVault(mirror){requireSecurePrimitives();db??=await openVault();key=await dbGet(db,KEY_ID);let rawPrimary=await dbGet(db,PRIMARY_ID),hadStoredState=rawPrimary!=null||mirror!=null,usableKey=isVerificationKey(key),primary=usableKey?await verifyEnvelope(rawPrimary):null,secondary=usableKey?await verifyEnvelope(mirror):null,chosen=null,integrityIssue=false;if(primary&&secondary){chosen=primary.envelope.r>=secondary.envelope.r?primary:secondary;integrityIssue=primary.envelope.r!==secondary.envelope.r||primary.envelope.p!==secondary.envelope.p}else{chosen=primary||secondary;integrityIssue=hadStoredState}if(!chosen){let snapshot=freshSnapshot(),envelope=await installSnapshot(snapshot,1);return {snapshot,mirror:JSON.stringify(envelope),revision:envelope.r,integrityIssue:hadStoredState}}if(!isVerifyOnlyKey(key)){let envelope=await installSnapshot(chosen.snapshot,chosen.envelope.r+1);return {snapshot:chosen.snapshot,mirror:JSON.stringify(envelope),revision:envelope.r,integrityIssue}}if(!primary||chosen===secondary)await dbPut(db,PRIMARY_ID,chosen.envelope);currentEnvelope=chosen.envelope;currentSnapshot=chosen.snapshot;return {snapshot:chosen.snapshot,mirror:JSON.stringify(chosen.envelope),revision:chosen.envelope.r,integrityIssue}}
async function refreshCurrentVault(){let storedKey=await dbGet(db,KEY_ID);if(!isVerifyOnlyKey(storedKey))throw new Error('Vault verification key is unavailable');key=storedKey;let latest=await verifyEnvelope(await dbGet(db,PRIMARY_ID));if(!latest)throw new Error('Vault changed or failed integrity validation');currentEnvelope=latest.envelope;currentSnapshot=latest.snapshot}
async function commitVault(input,reason,expectedRevision,expectedPayoutSequence=0){await refreshCurrentVault();if(!Number.isSafeInteger(expectedRevision)||expectedRevision!==currentEnvelope.r)throw new Error('Save is stale because another tab changed the vault');if(expectedPayoutSequence!==(currentSnapshot.airportBridge?.consumedSequence||0))throw new Error('An airport payout changed this wallet. Reload before saving.');if(!validateSnapshot(input,false))throw new Error('Snapshot failed semantic validation');let snapshot=appendLedger(currentSnapshot,{balance:input.balance,history:input.history.slice(0,8),stats:input.stats,progress:input.progress,airportBridge:currentSnapshot.airportBridge},reason);if(!validateSnapshot(snapshot,true))throw new Error('Ledger validation failed');let envelope=await installSnapshot(snapshot,currentEnvelope.r+1);return {mirror:JSON.stringify(envelope),revision:envelope.r,payoutSequence:snapshot.airportBridge?.consumedSequence||0}}

const airportBridge=createAirportBridge({getSnapshot:()=>currentSnapshot,getRevision:()=>currentEnvelope.r,install:installSnapshot,appendLedger,maxBalance:MAX_BALANCE});
async function loadWithAirportReceipts(mirror){const original=await loadVault(mirror);await airportBridge.ensureIdentity();let airportWarning=null;try{await airportBridge.reconcile()}catch(error){airportWarning=error.message}return {...original,snapshot:currentSnapshot,mirror:JSON.stringify(currentEnvelope),revision:currentEnvelope.r,payoutSequence:currentSnapshot.airportBridge.consumedSequence,airportWarning}}

let sessionToken='',authorityGranted=false,authorityLease;
function validSessionToken(value){return typeof value==='string'&&/^[a-f0-9]{64}$/.test(value)}
function sameToken(value){if(!validSessionToken(value)||value.length!==sessionToken.length)return false;let difference=0;for(let i=0;i<value.length;i++)difference|=value.charCodeAt(i)^sessionToken.charCodeAt(i);return difference===0}
async function claimAuthority(token){requireSecurePrimitives();if(!globalThis.navigator?.locks?.request)throw new Error('Secure Web Locks are required for protected offline saves');if(authorityGranted)throw new Error('Vault authority is already initialized');if(!validSessionToken(token))throw new Error('Vault session token is invalid');let settle,ready=new Promise(resolve=>settle=resolve);authorityLease=navigator.locks.request(AUTHORITY_LOCK,{mode:'exclusive',ifAvailable:true},async lock=>{settle(!!lock);if(!lock)return;await new Promise(()=>{})}).catch(()=>settle(false));if(!await ready)throw new Error('Dorra is already open in another tab or another vault worker is active');sessionToken=token;authorityGranted=true;return {secured:true}}

let mutationQueue=Promise.resolve();
self.onmessage=event=>{const {id,type,token,payload}=event.data||{};const operation=mutationQueue.then(async()=>{try{let result;if(type==='initialize')result=await claimAuthority(token);else{if(!authorityGranted||!sameToken(token))throw new Error('Vault request is not authorized for this session');if(type==='load')result=await loadWithAirportReceipts(payload?.mirror||null);else if(type==='commit')result=await commitVault(payload?.snapshot,payload?.reason,payload?.expectedRevision,payload?.expectedPayoutSequence);else if(['airport-load','airport-command','airport-withdraw','airport-developer'].includes(type)){await refreshCurrentVault();result=type==='airport-developer'?await airportBridge.developer(payload):type==='airport-load'?await airportBridge.load():type==='airport-command'?await airportBridge.command(payload):await airportBridge.withdraw(payload);result.mirror=JSON.stringify(currentEnvelope)}else throw new Error('Unsupported vault operation')}self.postMessage({id,ok:true,result})}catch(error){self.postMessage({id,ok:false,error:error?.message||'Vault operation failed',code:error.code,mirror:currentEnvelope?JSON.stringify(currentEnvelope):null,revision:currentEnvelope?.r})}});mutationQueue=operation.catch(()=>{});};
