import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {baseURL,supabaseHost,responseHeaders,launchBrowser,serveSource} from './browser-helpers.mjs';
import {initializeHouse} from '../supabase/functions/dorra-api/house-progression.mjs';
const actorId='11111111-1111-4111-8111-111111111111',targetId='22222222-2222-4222-8222-222222222222';
const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url');
function auth(role='admin'){const user={id:actorId,email:'fixture@example.test',aud:'authenticated',role:'authenticated',user_metadata:{username:'Fixture',role}};const access_token=`${encode({alg:'HS256'})}.${encode({sub:actorId,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})}.fixture`;return {access_token,refresh_token:'fixture-refresh',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user};}
const player={userId:targetId,username:'Riley Chen',displayName:'Riley Chen',role:'player',owner:false,status:'active',createdAt:'2026-09-12T04:00:00Z',lastPlayedAt:'2026-10-08T04:31:00Z',hasSave:true,level:12,xp:120,rounds:128,wins:64,revision:1,resources:{money:24500,footballClub:false,footballTokens:null,airportCareer:false,airports:[],owned:[]}};
const activity=[{id:targetId,actor:'Jamie Stone',targetId,target:'Riley Chen',action:'money',reason:'Support correction',changes:[{label:'Play money',before:14500,after:24500}],outcome:'success',createdAt:'2026-10-08T04:32:00Z'},...[["Sam Lee","Morgan Vale","report-resolve",'04:18'],["Jamie Stone","Alex Quinn","level",'03:55'],["Taylor Kim","Casey Park","money",'02:41'],["Chris Palmer","Jordan Mills","warn",'01:27']].map(([actor,target,action,time])=>({id:targetId,actor,targetId,target,action,reason:'Fixture QA',changes:[],outcome:'success',createdAt:`2026-10-08T${time}:00Z`}))];
async function setup(role='admin',override){const browser=await launchBrowser(),context=await browser.newContext({viewport:{width:1440,height:1024}}),calls=[];
  await context.addInitScript(session=>localStorage.setItem('dorra-online-auth',JSON.stringify(session)),auth(role));
  await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.hostname!==supabaseHost)return serveSource(route);if(request.method()==='OPTIONS')return route.fulfill({status:204,headers:responseHeaders,body:''});if(url.pathname==='/auth/v1/user')return route.fulfill({status:200,headers:responseHeaders,body:JSON.stringify(auth(role).user)});
    const body=request.postDataJSON();calls.push(body);let result={status:200,data:{}};
    if(body.scope){const snapshot={balance:1000,history:[],stats:{sessions:0,wins:0,games:{}},progress:{level:1,xp:0,owned:[],equipped:{},configurations:{},vehicles:{},profile:{name:'Profile fixture'}}};initializeHouse(snapshot,Date.now());snapshot.progress.arrival.complete=true;return route.fulfill({status:200,headers:responseHeaders,body:JSON.stringify({snapshot,revision:calls.length,username:'Profile fixture',serverNow:Date.now(),result:{highCard:{s:'♠',r:'K',v:10,red:false}}})});}
    if(body.operation==='status')result.data={userId:actorId,username:'Jamie Stone',role,owner:role==='admin',unlocked:true,expiresAt:new Date(Date.now()+1800000).toISOString()};
    if(body.operation==='dashboard')result.data={activePlayers:128,openReports:12,flaggedActivity:4,gameChanges:23,activity,serverNow:new Date().toISOString()};
    if(body.operation==='players')result.data={rows:body.args.search==='missing'?[]:[player],offset:0,total:body.args.search==='missing'?0:1};
    if(body.operation==='player')result.data={player:{...player,resources:role==='moderator'?null:player.resources},history:activity,flags:[],unlockCatalog:[]};
    if(body.operation==='reports'||body.operation==='staff'||body.operation==='activity')result.data={rows:[],offset:0,total:0};
    if(override)result=await override(body,result,calls);
    return route.fulfill({status:result.status,headers:responseHeaders,body:JSON.stringify(result.data)});
  });return {browser,context,calls};}
test('ordinary account with forged metadata cannot render admin data', {timeout:120000},async()=>{const {browser,context,calls}=await setup('admin',body=>({status:403,data:{code:'STAFF_REQUIRED',error:'This account is not approved for staff access.'}}));try{const page=await context.newPage();await page.goto(baseURL+'admin.html');await page.getByRole('heading',{name:'Permission denied'}).waitFor();assert.equal(calls.length,1);assert.equal(calls[0].operation,'status');assert.equal(await page.locator('.metrics').count(),0);}finally{await browser.close();}});
test('dashboard, search and resource confirmation recover from failed save with the same request ID', {timeout:120000},async()=>{let commits=0;const {browser,context,calls}=await setup('admin',(body,result)=>{
  if(body.operation==='preview')result.data={id:targetId,target:'Riley Chen',changes:[{label:'Play money',before:24500,after:24600}],reason:body.args.reason,expiresAt:new Date(Date.now()+300000).toISOString()};
  if(body.operation==='commit'){commits++;return commits===1?{status:503,data:{code:'SAVE_FAILED',error:'Please retry.'}}:{status:200,data:{ok:true}};}
  return result;
});try{const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(baseURL+'admin.html');await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>document.querySelector('#accessClock').textContent.includes('remaining'));await mkdir('work/admin-qa',{recursive:true});await page.screenshot({path:'work/admin-qa/dashboard-1440.png'});
  assert.equal(await page.locator('.metric strong').allTextContents().then(a=>a.join(',')),'128,12,4,23');assert.equal(await page.getByText('Needs review').count(),0);
  await page.getByRole('link',{name:'Players',exact:true}).click();await page.getByRole('textbox',{name:'Search by username'}).fill('missing');await page.getByRole('button',{name:'Apply filters'}).click();await page.getByRole('heading',{name:'No matching players'}).waitFor();await page.getByRole('button',{name:'Clear filters'}).click();await page.getByRole('link',{name:'Riley Chen',exact:true}).click();
  await page.getByRole('button',{name:'Resources',exact:true}).click();await page.getByRole('button',{name:'Adjust play money',exact:true}).click();await page.getByRole('spinbutton',{name:'Amount',exact:true}).fill('100');await page.getByRole('textbox',{name:'Reason',exact:true}).fill('Verified support correction');await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByRole('button',{name:'Confirm change',exact:true}).click();await page.getByRole('button',{name:'Retry confirmation',exact:true}).waitFor();await page.getByRole('button',{name:'Retry confirmation',exact:true}).click();await page.getByText('Change saved and recorded in activity.').waitFor();
  const committed=calls.filter(c=>c.operation==='commit');assert.equal(committed.length,2);assert.equal(committed[0].requestId,committed[1].requestId);
  await page.setViewportSize({width:1280,height:800});await page.reload();await page.getByRole('link',{name:'Dashboard',exact:true}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'work/admin-qa/dashboard-1280.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
}finally{await browser.close();}});
test('moderator controls hide resources and permanent bans; unavailable careers stay disabled', {timeout:120000},async()=>{
  const {browser,context}=await setup('moderator');try{const page=await context.newPage();await page.goto(baseURL+'admin.html#player/'+targetId);await page.getByRole('heading',{name:'Riley Chen'}).waitFor();assert.equal(await page.getByRole('button',{name:'Resources',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Permanently ban',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Warn player',exact:true}).count(),1);}finally{await browser.close();}
  const admin=await setup();try{const page=await admin.context.newPage();await page.goto(baseURL+'admin.html#player/'+targetId);await page.getByRole('heading',{name:'Riley Chen'}).waitFor();await page.getByRole('button',{name:'Resources',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Adjust football tokens',exact:true}).isDisabled(),true);await page.getByRole('heading',{name:'Airport career unavailable'}).waitFor();}finally{await admin.browser.close();}
});
test('code input clears immediately and rejected code leaves no sensitive data visible', {timeout:120000},async()=>{const {browser,context}=await setup('admin',(body,result)=>{if(body.operation==='status')result.data.unlocked=false;if(body.operation==='unlock')return {status:403,data:{code:'INVALID_CODE',error:'The access code is invalid.'}};return result;});try{const page=await context.newPage();await page.goto(baseURL+'admin.html');await page.getByRole('textbox',{name:'Access code',exact:true}).fill('DH-'+'a'.repeat(43));await page.getByRole('button',{name:'Unlock panel',exact:true}).click();await page.getByText('The access code is invalid.',{exact:true}).waitFor();assert.equal(await page.locator('#accessCode').inputValue(),'');assert.equal(await page.locator('.metrics').count(),0);}finally{await browser.close();}});

test('game profile helpers remain functional and Codes uses the protected staff endpoint', {timeout:120000},async()=>{const {browser,context,calls}=await setup('player',(body,result)=>body.operation==='unlock'?{status:403,data:{code:'STAFF_REQUIRED',error:'This account is not approved for staff access.'}}:result);try{const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(baseURL+'index.html');await page.getByRole('button',{name:'Open profile and settings',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();const code='DH-'+'a'.repeat(43);await page.getByRole('textbox',{name:'Gift code',exact:true}).fill(code);await page.getByRole('button',{name:'Redeem',exact:true}).click();await page.getByText('This account is not approved for staff access.',{exact:true}).waitFor();assert.equal(calls.filter(c=>c.operation==='unlock').length,1);assert.deepEqual(errors,[]);assert.equal(await page.evaluate(code=>[...Object.values(localStorage),...Object.values(sessionStorage)].some(value=>value.includes(code)),code),false);await page.getByRole('button',{name:'Edit profile',exact:true}).click();await page.getByRole('textbox',{name:'Display name',exact:true}).waitFor();}finally{await browser.close();}});

test('manual lock keeps its locked clock and discards an in-flight player response', {timeout:120000},async()=>{let release;const pending=new Promise(resolve=>release=resolve);const {browser,context}=await setup('admin',async(body,result)=>{if(body.operation==='players')await pending;return result;});try{const page=await context.newPage();await page.goto(baseURL+'admin.html');await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();await page.getByRole('link',{name:'Players',exact:true}).click();await page.getByRole('heading',{name:'Loading',exact:true}).waitFor();await page.getByRole('button',{name:'Admin',exact:true}).click();await page.getByRole('button',{name:'Lock panel',exact:true}).click();await page.getByRole('heading',{name:'Staff access',exact:true}).waitFor();release();await page.waitForTimeout(1300);assert.equal(await page.locator('#accessClock').innerText(),'Panel locked');assert.equal(await page.getByRole('heading',{name:'Staff access',exact:true}).count(),1);assert.equal(await page.getByRole('link',{name:'Riley Chen',exact:true}).count(),0);}finally{release();await browser.close();}});

test('expiry closes and clears a pending preview without letting its response repaint', {timeout:120000},async()=>{let release;const pending=new Promise(resolve=>release=resolve);const {browser,context}=await setup('admin',async(body,result)=>{if(body.operation==='status')result.data.expiresAt=new Date(Date.now()+5000).toISOString();if(body.operation==='preview'){await pending;result.data={id:targetId,target:'Riley Chen',reason:body.args.reason,changes:[{label:'Play money',before:24500,after:24600}],expiresAt:new Date(Date.now()+300000).toISOString()};}return result;});try{const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(baseURL+'admin.html#player/'+targetId);await page.getByRole('button',{name:'Resources',exact:true}).click();await page.getByRole('button',{name:'Adjust play money',exact:true}).click();await page.getByRole('spinbutton',{name:'Amount',exact:true}).fill('100');await page.getByRole('textbox',{name:'Reason',exact:true}).fill('Expiry fixture');await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByRole('heading',{name:'Staff access',exact:true}).waitFor();release();await page.waitForTimeout(300);assert.equal(await page.locator('#actionDialog[open]').count(),0);assert.equal(await page.locator('#dialogContent').innerText(),'');assert.equal(await page.getByRole('button',{name:'Confirm change',exact:true}).count(),0);assert.deepEqual(errors,[]);}finally{release();await browser.close();}});
