import test from 'node:test';
import assert from 'node:assert/strict';
import {cars} from '../supabase/functions/dorra-api/house-catalog.mjs';
import {reduceHouse} from '../supabase/functions/dorra-api/house.mjs';
import {normalizeProgression} from '../progression-engine.js';
const NOW=Date.parse('2026-10-07T12:00:00Z');
function fixture(){return {snapshot:{balance:2_000_000,history:[],stats:{sessions:0,wins:0,games:{}},progress:{level:7,xp:0,owned:['iphonex']}},privateState:{}}}
async function act(f,action,args={},now=NOW){const result=await reduceHouse(structuredClone(f.snapshot),structuredClone(f.privateState),action,args,now);f.snapshot=result.snapshot;f.privateState=result.privateState;return result.result}

test('existing office records adopt House wording without changing saved amounts or progress',async()=>{
 const progress={office:{transactions:[{type:'income',label:'Casino Empire collection',amount:350,at:NOW},{type:'trading',label:'Casino Empire · Week 12',amount:-200,at:NOW},{type:'upgrade',label:'Terrace · Level 2',amount:-1000,at:NOW}]}};
 normalizeProgression(progress,NOW);
 assert.deepEqual(progress.office.transactions.map(item=>item.label),['House Empire collection','House Empire · Week 12','Terrace · Level 2']);
 assert.deepEqual(progress.office.transactions.map(item=>item.amount),[350,-200,-1000]);
 assert(progress.office.transactions.every(item=>item.at===NOW));
 const f=fixture();f.snapshot.progress.office=progress.office;
 await act(f,'view');
 assert.deepEqual(f.snapshot.progress.office.transactions,progress.office.transactions);
});
test('all table games settle server-derived outcomes and no hidden deck is returned',async()=>{
 const f=fixture();await act(f,'view');
 for(const [game,args]of Object.entries({roulette:{choice:'red'},dice:{choice:'seven'},baccarat:{choice:'player'},highlow:{choice:'higher'},sicbo:{choice:'triple'},slots:{machine:'classic'},racing:{choice:0}})){const previous=f.snapshot.stats.sessions,r=await act(f,'casino',{game,move:'play',bet:25,...args,payout:999999999,won:true});assert.equal(f.snapshot.stats.sessions,previous+1);assert(Number.isSafeInteger(f.snapshot.balance));assert.equal(r.game,game);assert(!JSON.stringify(r).includes('deck'))}
 for(const game of ['bj','poker','holdem','videopoker']){let r=await act(f,'casino',{game,move:'start',bet:25});assert(!JSON.stringify(r).includes('deck'));if(game==='holdem')assert.equal(r.round.board.length,3);if(game==='poker'||game==='holdem')assert(r.round.dealer.every(c=>c.r===''));if(!r.round.finished)r=await act(f,'casino',{game,move:game==='bj'?'stand':game==='videopoker'?'draw':'fold',held:[0,1]});assert(r.round.finished);await assert.rejects(()=>act(f,'casino',{game,move:game==='bj'?'stand':game==='videopoker'?'draw':'fold'}),/already|first|hand/i)}
});
test('wagers respect server balance, level, positive integers, and no outcome action exists',async()=>{const f=fixture();f.snapshot.progress.level=1;await assert.rejects(()=>act(f,'casino',{game:'slots',bet:25,move:'play',machine:'classic'}),/locked/);for(const bet of [-5,0,0.5,101])await assert.rejects(()=>act(f,'casino',{game:'bj',move:'start',bet}));await assert.rejects(()=>act(f,'finishBJ',{result:'blackjack'}),/Unknown/)});
test('memory concealed cards stay private and server records misses/matches',async()=>{const f=fixture();const r=await act(f,'casino',{game:'memory',move:'start',bet:25});assert(r.round.values.every(v=>v===null));assert(f.snapshot.progress.activeHouseRounds.memory.values.every(v=>v===null));const secret=f.privateState.house.rounds.memory.deck;let first=0,second=secret.findIndex((v,i)=>i!==first&&v===secret[first]);let reveal=await act(f,'casino',{game:'memory',move:'pick',index:first});assert.equal(reveal.round.values.filter(v=>v!==null).length,1);reveal=await act(f,'casino',{game:'memory',move:'pick',index:second});assert.equal(reveal.round.matched.length,2);await assert.rejects(()=>act(f,'casino',{game:'memory',move:'pick',index:first}));});
test('Monte validates shuffle readiness and settles a round once',async()=>{const f=fixture(),r=await act(f,'casino',{game:'monte',move:'start',bet:25});assert.equal(r.swaps.length,8);assert(!('queen' in r));await assert.rejects(()=>act(f,'casino',{game:'monte',move:'pick',index:0},NOW+100));const queen=f.privateState.house.rounds.monte.queen,settled=await act(f,'casino',{game:'monte',move:'pick',index:queen},NOW+3000);assert.equal(settled.payout,50);await assert.rejects(()=>act(f,'casino',{game:'monte',move:'pick',index:queen},NOW+4000));});
test('catalog purchases derive prices and reject arbitrary configurations',async()=>{const f=fixture();await act(f,'view');const initial=f.snapshot.balance;await act(f,'phone-save',{id:'iphone17',model:'17',finish:'Black',storage:'256GB',case:'None',engraving:'Hello',wallpaper:'Emerald',price:0});assert(f.snapshot.balance<initial);assert(f.snapshot.progress.owned.includes('iphone17'));await assert.rejects(()=>act(f,'phone-save',{id:'iphone17',model:'17',finish:'Black',storage:'FREE',case:'None',wallpaper:'Emerald'}));await act(f,'car-save',{id:'porsche911',trim:0,upgrades:[],paint:cars[0].visuals.paint[0][0],aero:cars[0].visuals.aero[0][0],price:0});assert.equal(f.snapshot.progress.vehicles.porsche911.price,280000);await assert.rejects(()=>act(f,'car-save',{id:'porsche911',trim:0,upgrades:['fake'],paint:'base',aero:'standard'}));await assert.rejects(()=>act(f,'equip',{id:'iphone16'}));});
test('markets keep future events private, enforce clock, prices, and reserved funds',async()=>{const f=fixture();await act(f,'app-buy',{id:'markets'});for(let tick=0;tick<5;tick++)await act(f,'market-tick',{},NOW+tick*12000);const market=f.snapshot.progress.market;assert(market.events.some(e=>!e.applied));assert(market.events.filter(e=>!e.applied).every(e=>!('direction'in e)&&!('magnitude'in e)));await assert.rejects(()=>act(f,'market-tick',{},NOW+49000),/not ready/);const balance=f.snapshot.balance;await act(f,'market-trade',{symbol:'DORRA',side:'buy',qty:1,price:0,total:0},NOW+50000);assert(f.snapshot.balance<balance);assert.equal(f.snapshot.progress.market.holdings.DORRA.shares,1);await assert.rejects(()=>act(f,'market-trade',{symbol:'DORRA',side:'sell',qty:2},NOW+50000),/shares/);await act(f,'market-order',{symbol:'DORRA',side:'sell',qty:1,type:'limit',limit:100000,tif:'gtc'},NOW+50000);await assert.rejects(()=>act(f,'market-trade',{symbol:'DORRA',side:'sell',qty:1},NOW+50000),/shares/);await act(f,'market-cancel',{id:f.snapshot.progress.market.orders.at(-1).id},NOW+50000);await act(f,'market-trade',{symbol:'DORRA',side:'sell',qty:1},NOW+50000);assert(!f.snapshot.progress.market.holdings.DORRA);});
test('pocket app keeps quotes server-owned and settles integer shared wallet',async()=>{const f=fixture();await act(f,'app-buy',{id:'pocket'});await act(f,'pocket-tick');await act(f,'pocket-trade',{symbol:'BZZY',side:'buy',qty:100,price:0});assert.equal(f.snapshot.progress.pocket.holdings.BZZY.shares,100);assert(Number.isSafeInteger(f.snapshot.balance));await act(f,'pocket-trade',{symbol:'BZZY',side:'sell',qty:100});assert(!f.snapshot.progress.pocket.holdings.BZZY)});
test('normal accounts have no resource-editing or developer action',async()=>{const f=fixture();for(const action of ['developer','developer-money','developer-football-tokens','airport-developer','commit'])await assert.rejects(()=>act(f,action,{balance:999999999999,level:99}),/Unknown/)});

test('fractional Pocket prices cannot mint whole dollars by repeated buy/sell cycles',async()=>{const f=fixture();await act(f,'app-buy',{id:'pocket'});await act(f,'pocket-tick');f.snapshot.progress.pocket.quotes.BZZY.price=.345;const balance=f.snapshot.balance;for(let i=0;i<5;i++){await act(f,'pocket-trade',{symbol:'BZZY',side:'buy',qty:100});await act(f,'pocket-trade',{symbol:'BZZY',side:'sell',qty:100})}assert(f.snapshot.balance<=balance);assert(Number.isSafeInteger(f.snapshot.balance))});

test('market history retention cannot discard open orders',async()=>{const f=fixture();await act(f,'app-buy',{id:'markets'});await act(f,'market-tick');const m=f.privateState.house.market;m.orders=Array.from({length:29},(_,i)=>({id:'open-'+i,symbol:'DORRA',side:'buy',qty:1,type:'limit',limit:1,tif:'gtc',status:'open',at:NOW+i}));m.orders.push({id:'old-filled',status:'filled',at:NOW+30},{id:'last-open',symbol:'DORRA',side:'buy',qty:1,type:'limit',limit:1,tif:'gtc',status:'open',at:NOW+31});await act(f,'market-tick',{},NOW+12000);assert.equal(f.snapshot.progress.market.orders.filter(o=>o.status==='open').length,30);assert(f.snapshot.progress.market.orders.some(o=>o.id==='open-0'))});
