-- Rollback-only owner controls and authorization regression fixtures.
begin;
do $$ declare
 owner_id uuid:=gen_random_uuid(); admin_id uuid:=gen_random_uuid(); player_id uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
 owner_session uuid:=gen_random_uuid(); admin_session uuid:=gen_random_uuid(); player_session uuid:=gen_random_uuid(); outsider_session uuid:=gen_random_uuid(); lease uuid:=gen_random_uuid();
 snapshot jsonb:='{"balance":1000,"stats":{"sessions":10,"wins":4},"progress":{"level":2,"xp":10,"owned":[],"equipped":{}}}';
 output jsonb; preview jsonb; claim jsonb; req uuid:=gen_random_uuid(); msg uuid; rev bigint; version bigint;
begin
 insert into auth.users(id,email,raw_user_meta_data) select u,u||'@dorra-qa.invalid',jsonb_build_object('username','qa_'||substr(u::text,1,8)) from unnest(array[owner_id,admin_id,player_id,outsider]) u;
 insert into auth.sessions(id,user_id) values(owner_session,owner_id),(admin_session,admin_id),(player_session,player_id),(outsider_session,outsider);
 update dorra_private.profiles set role='admin',owner=true where user_id=owner_id;
 update dorra_private.profiles set role='admin' where user_id=admin_id;
 output:=public.dorra_admin_grant(owner_id,owner_session,dorra_private.code_version());
 if not (output->>'unlimited')::boolean or output->>'expiresAt' is not null then raise exception 'FAIL_OWNER_UNLIMITED'; end if;
 output:=public.dorra_admin_grant(admin_id,admin_session,dorra_private.code_version());
 if (output->>'unlimited')::boolean or (output->>'expiresAt')::timestamptz>now()+interval '30 minutes 1 second' then raise exception 'FAIL_ADMIN_EXPIRY'; end if;
 update dorra_private.admin_grants set expires_at=null where user_id=admin_id;
 begin perform public.dorra_admin_read(admin_id,admin_session,'dashboard','{}');raise exception 'FAIL_ADMIN_NULL_EXPIRY';exception when others then if sqlerrm not like '%ACCESS_EXPIRED%' then raise;end if;end;
 perform public.dorra_admin_grant(admin_id,admin_session,dorra_private.code_version());
 begin perform public.dorra_admin_read(admin_id,admin_session,'online','{}');raise exception 'FAIL_ADMIN_ONLINE';exception when others then if sqlerrm not like '%PERMISSION_DENIED%' then raise;end if;end;
 begin perform public.dorra_admin_preview(admin_id,admin_session,player_id,null,1,'{"action":"save-field","reason":"Fixture"}','[]','digest',snapshot,'{}');raise exception 'FAIL_ADMIN_OWNER_EDIT';exception when others then if sqlerrm not like '%PERMISSION_DENIED%' then raise;end if;end;
 output:=public.dorra_acquire_session(player_id,player_session,lease,snapshot);rev:=(output->>'revision')::bigint;
 output:=public.dorra_player_pulse(player_id,player_session,lease,true);
 if not exists(select 1 from dorra_private.online_players() where user_id=player_id) then raise exception 'FAIL_PRESENCE';end if;
 begin perform public.dorra_player_pulse(outsider,outsider_session,lease,true);raise exception 'FAIL_FOREIGN_PULSE';exception when others then if sqlerrm not like '%SESSION_REPLACED%' then raise;end if;end;
 select admin_version into version from dorra_private.profiles where user_id=player_id;
 preview:=public.dorra_admin_preview(owner_id,owner_session,player_id,rev,version,'{"action":"announcement","title":"Fixture","message":"Literal text","duration":10,"audience":"online","reason":"QA"}','[]','message',null,null);
 output:=public.dorra_admin_commit(owner_id,owner_session,(preview->>'id')::uuid,gen_random_uuid());msg:=(output->>'recordId')::uuid;
 output:=public.dorra_player_pulse(player_id,player_session,lease,true);
 if jsonb_array_length(output->'messages')<>1 then raise exception 'FAIL_MESSAGE_DELIVERY'; end if;
 begin perform public.dorra_player_pulse(outsider,outsider_session,lease,false);raise exception 'FAIL_FOREIGN_MESSAGE';exception when others then if sqlerrm not like '%SESSION_REPLACED%' then raise;end if;end;
 perform public.dorra_player_dismiss(player_id,player_session,msg);
 if jsonb_array_length(public.dorra_player_pulse(player_id,player_session,lease,true)->'messages')<>0 then raise exception 'FAIL_DISMISS';end if;
 begin perform public.dorra_player_dismiss(outsider,outsider_session,msg);raise exception 'FAIL_FOREIGN_DISMISS';exception when others then if sqlerrm not like '%NOT_FOUND%' then raise;end if;end;
 update dorra_private.player_presence set last_seen=now()-interval '91 seconds' where user_id=player_id;
 if exists(select 1 from dorra_private.online_players() where user_id=player_id) then raise exception 'FAIL_PRESENCE_EXPIRY';end if;
 select admin_version into version from dorra_private.profiles where user_id=player_id;
 preview:=public.dorra_admin_preview(owner_id,owner_session,player_id,rev,version,'{"action":"save-field","reason":"QA"}','[]','save',jsonb_set(snapshot,'{balance}','1100'),'{}');
 output:=public.dorra_admin_commit(owner_id,owner_session,(preview->>'id')::uuid,gen_random_uuid());
 if (select s.snapshot->>'balance' from dorra_private.player_state s where s.user_id=player_id)<>'1100' then raise exception 'FAIL_SAVE_COMMIT';end if;
 select s.revision,p.admin_version into rev,version from dorra_private.player_state s join dorra_private.profiles p using(user_id) where s.user_id=player_id;
 preview:=public.dorra_admin_preview(owner_id,owner_session,player_id,rev,version,jsonb_build_object('action','password-set','reason','QA','confirmation',(select username from dorra_private.profiles where user_id=player_id)),'[]','password',null,null);
 perform set_config('role','service_role',true);
 claim:=public.dorra_owner_password_begin(owner_id,owner_session,(preview->>'id')::uuid,req,repeat('a',64));
 begin perform public.dorra_owner_password_begin(admin_id,admin_session,(preview->>'id')::uuid,gen_random_uuid(),repeat('a',64));raise exception 'FAIL_ADMIN_PASSWORD';exception when others then if sqlerrm not like '%PERMISSION_DENIED%' then raise;end if;end;
 perform public.dorra_owner_password_finish(owner_id,owner_session,(claim->>'jobId')::uuid,(claim->>'claim')::uuid,false);
 claim:=public.dorra_owner_password_begin(owner_id,owner_session,(preview->>'id')::uuid,req,repeat('a',64));
 perform public.dorra_owner_password_finish(owner_id,owner_session,(claim->>'jobId')::uuid,(claim->>'claim')::uuid,true);
 if exists(select 1 from auth.sessions where user_id=player_id) then raise exception 'FAIL_PASSWORD_SESSION_REVOKE';end if;
 output:=public.dorra_owner_password_begin(owner_id,owner_session,(preview->>'id')::uuid,req,repeat('a',64));
 if not(output->>'replayed')::boolean then raise exception 'FAIL_PASSWORD_REPLAY';end if;
 begin perform public.dorra_owner_password_begin(owner_id,owner_session,(preview->>'id')::uuid,req,repeat('b',64));raise exception 'FAIL_PASSWORD_BINDING';exception when others then if sqlerrm not like '%REQUEST_REUSED%' then raise;end if;end;
 delete from dorra_private.admin_grants where user_id=owner_id;
 begin perform public.dorra_admin_read(owner_id,owner_session,'dashboard','{}');raise exception 'FAIL_OWNER_REVOKED';exception when others then if sqlerrm not like '%ACCESS_EXPIRED%' then raise;end if;end;
 if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'dorra_%' and (has_function_privilege('anon',p.oid,'execute') or has_function_privilege('authenticated',p.oid,'execute'))) then raise exception 'FAIL_BROWSER_RPC';end if;
end $$;
select 'passed: owner expiry, role denial, presence, messages, atomic edits, password claims/retry/replay/revocation and browser denial' validation;
rollback;
