import {shop,cars,phoneFamilies,macbookFamilies,dorraMarketCompanies,dorraPerkCatalog,dorraMarketRates,dorraOsStoreCatalog,slotMachines,raceHorses,pocketCompanies} from './house-catalog.mjs';
import {suits,ranks,score,highValue,baccaratValue,baccaratScore,pokerRank,comparePoker,bestHoldem,videoPokerRank} from './house-card-rules.mjs';
import {createMarketEngine} from './house-market-engine.mjs';
import {initializeHouse,recordRoundResult,settleAchievements,recordOfficeTransaction,reduceHouseProgression} from './house-progression.mjs';
import {empirePerks} from './shared/progression-engine.js';
import {MAX_BALANCE} from './shared/game-limits.js';
const random=()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296;
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function deck(){return shuffle(suits.flatMap(s=>ranks.map((r,i)=>({s,r,v:i===0?11:Math.min(i+1,10),red:s==='♥'||s==='♦'}))))}
function need(condition,message='This action is not available.'){if(!condition)throw new Error(message)}
function whole(value,min=1,max=1e6){need(Number.isSafeInteger(value)&&value>=min&&value<=max,'Choose a valid whole-number amount.');return value}
function discount(s,price,type){const p=empirePerks(s.progress);return Math.round(price*(1-(type==='vehicle'?p.vehicleDiscountPct:p.boutiqueDiscountPct)))}
const tiers=[{level:1,cap:100,games:['bj','roulette','monte','memory']},{level:2,cap:100,games:['highlow','dice','slots']},{level:3,cap:250,games:['baccarat','poker','videopoker']},{level:4,cap:500,games:['holdem','sicbo','racing']},{level:5,cap:1000,games:[]},{level:7,cap:MAX_BALANCE,games:[]}];
function wager(s,game,bet){const tier=[...tiers].reverse().find(t=>s.progress.level>=t.level)||tiers[0],unlock=tiers.find(t=>t.games.includes(game))?.level||1;whole(bet,1,tier.cap);need(s.progress.level>=unlock,'This table is locked at your current level.');need(s.balance>=bet,'Not enough play money for this wager.');s.balance-=bet;return bet}
function publicRound(game,g){if(!g)return null;const r={bet:g.bet,phase:g.phase,finished:!!g.finished};if(['bj','poker','holdem'].includes(game)){r.player=g.player;r.dealer=g.finished?g.dealer:[g.dealer[0],{s:'',r:'',v:0,red:false}];if(game!=='bj'&&!g.finished)r.dealer=g.dealer.map(()=>({s:'',r:'',v:0,red:false}));if(g.board){r.board=g.board.slice(0,g.finished?5:3);r.visible=g.finished?5:3}r.canDouble=game==='bj'&&!g.hit&&!g.finished}if(game==='videopoker'){r.hand=g.hand;r.held=[]}if(game==='memory'){r.values=g.deck.map((v,i)=>g.matched.includes(i)||g.open.includes(i)?v:null);r.open=g.open;r.matched=g.matched;r.misses=g.misses;r.live=!g.finished}if(game==='monte')r.ready=!g.finished;return r}
function finish(s,h,g,game,name,won,message,payout,now,extra={}){need(!g.finished,'This round has already settled.');s.balance=Math.min(MAX_BALANCE,s.balance+payout);g.finished=true;g.phase='result';recordRoundResult(s,{game:name,won,bet:g.bet,message:`${name}: ${message}`},now);return {game,message,payout,won,round:publicRound(game,g),...extra}}
export async function reduceHouse(snapshot,privateState,action,args={},now=Date.now()){
 initializeHouse(snapshot,now);privateState.house??={};const h=privateState.house;h.rounds??={};let result={message:'Saved.'};
 const progression=await reduceHouseProgression(snapshot,privateState,action,args,now);if(progression)return progression;
 if(action==='view'){h.highCard??=deck().pop();result={highCard:h.highCard};}
 else if(action==='casino'){
  const game=String(args.game||''),move=String(args.move||'play');let g=h.rounds[game];const names={bj:'Blackjack',poker:'Three Card Poker',holdem:'Texas Hold’em',videopoker:'Video Poker',roulette:'Roulette',dice:'Lucky Dice',baccarat:'Baccarat',highlow:'High–Low',sicbo:'Sic Bo',racing:'Horse Racing',monte:'Three Card Monte',memory:'Memory Match'};
  need(names[game]||game==='slots','Unknown house table.');
  if(['bj','poker','holdem','videopoker','monte','memory'].includes(game)&&move==='start'){
   need(!g||g.finished,'Finish your current round first.');const bet=wager(snapshot,game,args.bet);g={bet,phase:'play',finished:false,deck:deck()};h.rounds[game]=g;
   if(game==='bj'){g.dealer=[g.deck.pop(),g.deck.pop()];g.player=[g.deck.pop(),g.deck.pop()];g.hit=false;if(score(g.player)===21)result=finish(snapshot,h,g,game,names[game],score(g.dealer)!==21,score(g.dealer)===21?'Push — wager returned.':'Blackjack — paid 3 to 2!',score(g.dealer)===21?bet:Math.floor(bet*2.5),now);else result={game,message:'Hit, stand, or double down.',round:publicRound(game,g)}}
   if(game==='poker'||game==='holdem'){const count=game==='poker'?3:2;g.player=Array.from({length:count},()=>g.deck.pop());g.dealer=Array.from({length:count},()=>g.deck.pop());if(game==='holdem')g.board=Array.from({length:5},()=>g.deck.pop());result={game,message:game==='poker'?'Play with an equal wager, or fold.':'Call one ante to reveal turn and river, or fold.',round:publicRound(game,g)}}
   if(game==='videopoker'){g.hand=Array.from({length:5},()=>g.deck.pop());g.phase='hold';result={game,message:'Choose cards to hold, then draw.',round:publicRound(game,g)}}
   if(game==='memory'){g.deck=shuffle(['A♠','A♥','K♣','K♦','Q♠','Q♥','A♠','A♥','K♣','K♦','Q♠','Q♥']);g.open=[];g.matched=[];g.misses=0;result={game,message:'Pairs found: 0 / 6 · Misses: 0 / 6',round:publicRound(game,g)}}
   if(game==='monte'){let order=['queen','jack-1','jack-2'];const swaps=[];let previous='';for(let i=0;i<8;i++){const options=[[0,1],[1,2],[0,2]].filter(p=>p.join('-')!==previous),pair=options[Math.floor(random()*options.length)];previous=pair.join('-');swaps.push(pair);[order[pair[0]],order[pair[1]]]=[order[pair[1]],order[pair[0]]]}g.queen=order.indexOf('queen');g.readyAt=now+1800;delete g.deck;result={game,message:'Where is the queen? Choose one card.',swaps,round:publicRound(game,g)}}
  }else if(game==='bj'){
   need(g&&!g.finished,'Deal a hand first.');need(['hit','stand','double'].includes(move));
   if(move==='double'){need(!g.hit&&g.player.length===2,'Double is available only on the opening hand.');need(snapshot.balance>=g.bet,'Not enough play money to double.');snapshot.balance-=g.bet;g.bet*=2;g.player.push(g.deck.pop());g.hit=true;}else if(move==='hit'){g.player.push(g.deck.pop());g.hit=true;}
   if(score(g.player)>21)result=finish(snapshot,h,g,game,names[game],false,'Bust. The house wins.',0,now);else if(move==='hit'&&score(g.player)<21)result={game,message:'Hit or stand.',round:publicRound(game,g)};else{while(score(g.dealer)<17)g.dealer.push(g.deck.pop());const ps=score(g.player),ds=score(g.dealer),won=ds>21||ps>ds,tie=ps===ds;result=finish(snapshot,h,g,game,names[game],won,won?'You beat the dealer.':tie?'Push — wager returned.':'Dealer wins this hand.',won?g.bet*2:tie?g.bet:0,now)}
  }else if(game==='poker'||game==='holdem'){
   need(g&&!g.finished,'Deal a hand first.');need(['play','call','fold'].includes(move));let won=false,payout=0,message='Folded — ante lost.';
   if(move!=='fold'){need(snapshot.balance>=g.bet,'Not enough play money to call.');snapshot.balance-=g.bet;const pr=game==='poker'?pokerRank(g.player):bestHoldem([...g.player,...g.board]),dr=game==='poker'?pokerRank(g.dealer):bestHoldem([...g.dealer,...g.board]),cmp=comparePoker(pr,dr);if(game==='poker'&&!(dr.score[0]>0||dr.score[1]>=12)){payout=g.bet*3;won=true;message='Dealer does not qualify — ante wins, play pushes.'}else{won=cmp>0;payout=cmp>0?g.bet*4:cmp===0?g.bet*2:0;message=cmp>0?`${pr.name} beats ${dr.name}.`:cmp===0?'Exact tie — both wagers returned.':`Dealer’s ${dr.name} wins.`}if(game==='poker'&&pr.bonus){payout+=g.bet*pr.bonus;message+=` Ante bonus +${pr.bonus}:1.`}}
   result=finish(snapshot,h,g,game,names[game],won,message,payout,now)
  }else if(game==='videopoker'){
   need(g&&!g.finished&&g.phase==='hold','Deal a hand first.');need(move==='draw');const held=args.held||[];need(Array.isArray(held)&&held.length<=5&&held.every(i=>Number.isInteger(i)&&i>=0&&i<5));g.hand=g.hand.map((c,i)=>held.includes(i)?c:g.deck.pop());const rank=videoPokerRank(g.hand),payout=g.bet*rank.payout;result=finish(snapshot,h,g,game,names[game],payout>g.bet,rank.payout?`${rank.name} — paid $${payout}.`:'No paying hand.',payout,now)
  }else if(game==='memory'){
   need(g&&!g.finished,'Start a memory round first.');need(move==='pick');const index=whole(args.index,0,11);need(!g.open.includes(index)&&!g.matched.includes(index));g.open.push(index);let message=`Pairs found: ${g.matched.length/2} / 6 · Misses: ${g.misses} / 6`,reveal=g.open.map(i=>({index:i,value:g.deck[i]}));if(g.open.length===2){const [a,b]=g.open;if(g.deck[a]===g.deck[b])g.matched.push(a,b);else g.misses++;g.open=[];if(g.matched.length===12)result=finish(snapshot,h,g,game,names[game],true,'All six pairs found.',g.bet*2,now,{reveal});else if(g.misses>=6)result=finish(snapshot,h,g,game,names[game],false,'Six misses — the house takes the round.',0,now,{reveal});else result={game,message:`Pairs found: ${g.matched.length/2} / 6 · Misses: ${g.misses} / 6`,round:publicRound(game,g),reveal}}else result={game,message,round:publicRound(game,g),reveal}
  }else if(game==='monte'){
   need(g&&!g.finished,'Start a Monte round first.');need(move==='pick'&&now>=g.readyAt,'Watch the shuffle first.');const index=whole(args.index,0,2),won=index===g.queen;result=finish(snapshot,h,g,game,names[game],won,won?'Queen found.':'Queen missed.',won?g.bet*2:0,now,{queen:g.queen})
  }else{
   need(move==='play');const bet=wager(snapshot,game,args.bet);g={bet,finished:false};let won=false,payout=0,message='',extra={};const choice=args.choice;
   if(game==='roulette'){need(['red','black','odd','even','low','high',...Array.from({length:37},(_,i)=>String(i))].includes(String(choice)));const n=Math.floor(random()*37),red=[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36].includes(n);won=String(n)===String(choice)||(n!==0&&((choice==='red'&&red)||(choice==='black'&&!red)||(choice==='odd'&&n%2===1)||(choice==='even'&&n%2===0)||(choice==='low'&&n<=18)||(choice==='high'&&n>=19)));payout=won?bet*(String(n)===String(choice)?36:2):0;message=`${n} ${n===0?'green':red?'red':'black'} — ${won?'you win $'+payout:'house wins'}`;extra={number:n};}
   if(game==='dice'){need(['low','high','seven'].includes(choice));const dice=[1+Math.floor(random()*6),1+Math.floor(random()*6)],sum=dice[0]+dice[1];won=(choice==='low'&&sum<=6)||(choice==='high'&&sum>=8)||(choice==='seven'&&sum===7);payout=won?bet*(choice==='seven'?5:2):0;message=`Rolled ${sum} — ${won?'paid $'+payout:'house wins'}.`;extra={dice}}
   if(game==='baccarat'){need(['player','banker','tie'].includes(choice));const d=deck(),player=[d.pop(),d.pop()],banker=[d.pop(),d.pop()];let ps=baccaratScore(player),bs=baccaratScore(banker),third=null;if(ps<8&&bs<8){if(ps<=5){third=d.pop();player.push(third)}if(!third){if(bs<=5)banker.push(d.pop())}else{const t=baccaratValue(third);if(bs<=2||(bs===3&&t!==8)||(bs===4&&t>=2&&t<=7)||(bs===5&&t>=4&&t<=7)||(bs===6&&t>=6&&t<=7))banker.push(d.pop())}}ps=baccaratScore(player);bs=baccaratScore(banker);const outcome=ps===bs?'tie':ps>bs?'player':'banker';won=choice===outcome;payout=won?(choice==='tie'?bet*9:choice==='banker'?Math.floor(bet*1.95):bet*2):0;message=`${outcome} wins ${ps}–${bs}. ${won?'Paid $'+payout+'.':'House takes the wager.'}`;extra={player,banker};}
   if(game==='highlow'){need(['higher','lower'].includes(choice));h.highCard??=deck().pop();const old=h.highCard,next=deck().pop(),a=highValue(old),b=highValue(next),tie=a===b;won=choice==='higher'?b>a:b<a;payout=tie?bet:won?bet*2:0;h.highCard=next;message=tie?'Tie — wager returned.':won?'Correct — paid 2×.':'Wrong call — house wins.';extra={card:next}}
   if(game==='sicbo'){const dice=Array.from({length:3},()=>1+Math.floor(random()*6)),sum=dice.reduce((a,b)=>a+b,0),triple=dice.every(n=>n===dice[0]),odds={4:50,5:18,6:14,7:12,8:8,9:6,10:6,11:6,12:6,13:8,14:12,15:14,16:18,17:50};need(['low','high','odd','even','triple',...Object.keys(odds).map(n=>'total-'+n)].includes(choice));let multi=2;if(choice==='triple'){won=triple;multi=31}else if(choice.startsWith('total-')){won=sum===Number(choice.slice(6));multi=(odds[sum]||0)+1}else won=!triple&&((choice==='low'&&sum>=4&&sum<=10)||(choice==='high'&&sum>=11&&sum<=17)||(choice==='odd'&&sum%2===1)||(choice==='even'&&sum%2===0));payout=won?bet*multi:0;message=`Rolled ${sum}${triple?' · triple':''} — ${won?'paid $'+payout:'house wins'}.`;extra={dice}}
   if(game==='slots'){const config=slotMachines[args.machine];need(config,'Choose a valid slot machine.');const roll=random();let floor=0,outcome;for(const symbol of config.symbols){floor+=symbol[3];if(roll<floor){outcome={symbol:symbol[0],multi:symbol[2],name:symbol[1]};break}}let reels;if(outcome){reels=Array(config.reels).fill(outcome.symbol);won=true;payout=bet*outcome.multi;message=`${outcome.name} across ${config.reels} reels — paid $${payout}.`}else{do{reels=Array.from({length:config.reels},()=>config.symbols[Math.floor(random()*config.symbols.length)][0])}while(reels.every(x=>x===reels[0]));message=`No ${config.reels}-reel match — house wins.`}extra={reels,machine:args.machine};result=finish(snapshot,h,g,game,config.name,won,message,payout,now,extra)}
   if(game==='racing'){const index=whole(choice,0,5),weights=raceHorses.map(r=>1/r.odds);let roll=random()*weights.reduce((a,b)=>a+b,0),winner=0;for(let i=0;i<weights.length;i++){roll-=weights[i];if(roll<=0){winner=i;break}}won=index===winner;payout=won?Math.floor(bet*raceHorses[index].odds):0;message=`${raceHorses[winner].name} wins — ${won?'paid $'+payout:'your runner was unplaced'}.`;extra={winner,order:[winner,...shuffle(raceHorses.map((_,i)=>i).filter(i=>i!==winner))]}}
   if(game!=='slots')result=finish(snapshot,h,g,game,names[game],won,message,payout,now,extra);
  }
 }
 else if(action.startsWith('market-')||action.startsWith('pocket-'))result=reduceMarket(snapshot,h,action,args,now);
 else if(['shop-buy','phone-save','mac-save','car-save','equip','display-car','wallpaper','perk-buy','perk-setting','app-buy'].includes(action))result=reduceCollection(snapshot,action,args,now);
 else throw new Error('Unknown house action.');
 if(snapshot.progress.osApps?.owned?.markets||snapshot.progress.osApps?.owned?.bloomberg){if(!h.market){createMarketEngine(snapshot,now).ensureDorraMarket();h.market=structuredClone(snapshot.progress.market)}snapshot.progress.market=structuredClone(h.market);if(!snapshot.progress.osApps?.owned?.bloomberg)snapshot.progress.market.events=snapshot.progress.market.events.map(event=>event.applied?event:{id:event.id,symbol:event.symbol,headline:'Company catalyst scheduled',impactTick:event.impactTick,applied:false,status:'scheduled',category:event.category,sourceStatus:'unavailable'})}
 snapshot.progress.activeHouseRounds=Object.fromEntries(Object.entries(h.rounds).filter(([,g])=>!g.finished).map(([name,g])=>[name,publicRound(name,g)]));snapshot.progress.highCard=h.highCard||null;settleAchievements(snapshot,now);snapshot.balance=Math.min(MAX_BALANCE,Math.max(0,Math.round(snapshot.balance)));return {snapshot,privateState,result};
}
function reduceCollection(s,action,a,now){const p=s.progress,owned=id=>p.owned.includes(id),pay=(price,label)=>{need(s.balance>=price,'Not enough play money.');s.balance-=price;recordOfficeTransaction(s,'purchase',-price,label,now)};let message='Saved.';
 if(action==='shop-buy'){const item=shop.find(x=>x.id===a.id);need(item&&p.level>=item.level&&!item.configurable&&!macbookFamilies[item.id]);if(!owned(item.id)){pay(discount(s,item.price,'boutique'),item.name);p.owned.push(item.id)}p.equipped[item.type]=item.id;message=`${item.name} equipped.`}
 if(action==='phone-save'){const f=phoneFamilies[a.id],v=f?.variants.find(x=>x[0]===a.model);need(v&&p.level>=(shop.find(x=>x.id===a.id)?.level||1));need(v[5].split('|').includes(a.storage)&&['None','Clear','Silicone'].includes(a.case)&&['Emerald','Oxblood','Midnight','Ivory'].includes(a.wallpaper));const finishes=v[10]?v[10].split('|').map(x=>x.split(':')[0]):f.finishes.map(x=>x[0]);need(finishes.includes(a.finish));const base=v[5].split('|')[0],extra=a.storage===base?0:a.storage==='2TB'?1400:a.storage==='1TB'?800:a.storage==='512GB'?400:a.storage==='256GB'?200:a.storage==='128GB'?100:0,price=discount(s,v[6]+extra+(a.case==='Clear'?80:a.case==='Silicone'?120:0),'boutique');if(!owned(a.id)){pay(price,v[1]);p.owned.push(a.id)}p.equipped.tech=a.id;p.configurations[a.id]={model:a.model,finish:a.finish,storage:a.storage,case:a.case,engraving:String(a.engraving||'').replace(/[<>"'&]/g,'').slice(0,20),wallpaper:a.wallpaper,price};message=`${v[1]} configuration saved.`}
 if(action==='mac-save'){need(p.level>=(shop.find(item=>item.id===a.id)?.level||1),'This computer is locked at your current level.');const m=macbookFamilies[a.id]?.models.find(x=>x.id===a.model),t=m?.tiers.find(x=>x.id===a.chip);need(m&&t);const option=(list,value)=>{const o=list.find(x=>x.name===value);need(o,'Choose a valid hardware option.');return Math.max(0,o.price-(list[0]?.price||0))};const powers=m.chassis==='air-wedge'?[{name:'30W USB-C',price:0}]:m.chassis==='pro-touchbar'?[{name:'61W USB-C',price:0}]:['air-13','air-15'].includes(m.chassis)?[{name:'35W dual USB-C',price:0},{name:'70W USB-C',price:30}]:m.chassis==='pro-16'?[{name:'140W USB-C',price:0}]:[{name:'70W USB-C',price:0},{name:'96W USB-C',price:30}];need(m.finishes.some(f=>f[0]===a.finish)&&['Emerald','Oxblood','Midnight','Ivory'].includes(a.wallpaper)&&['Standard glass',...(m.nano?['Nano-texture']:[])].includes(a.display));const price=discount(s,m.price+t.price+option(t.memory,a.memory)+option(t.storage,a.storage)+option(powers,a.power)+(a.display==='Nano-texture'?150:0),'boutique');if(!owned(a.id)){pay(price,m.name);p.owned.push(a.id)}p.equipped.computer=a.id;p.configurations[a.id]={model:m.id,chip:t.id,finish:a.finish,memory:a.memory,storage:a.storage,display:a.display,power:a.power,wallpaper:a.wallpaper,price};message=`${m.name} configuration saved.`}
 if(action==='car-save'){const c=cars.find(x=>x.id===a.id);need(c);const trim=whole(a.trim,0,c.trims.length-1),upgrades=a.upgrades||[];need(Array.isArray(upgrades)&&new Set(upgrades).size===upgrades.length);const opts=Object.values(c.upgrades).flat();need(upgrades.every(id=>opts.some(u=>u[0]===id)));const paint=(c.visuals?.paint||[['base','Base',0]]).find(o=>o[0]===a.paint),aero=(c.visuals?.aero||[['standard','Standard',0]]).find(o=>o[0]===a.aero);need(paint&&aero);const price=discount(s,c.base+5*(c.trims[trim][1]+opts.filter(o=>upgrades.includes(o[0])).reduce((sum,o)=>sum+o[2],0)+(paint[2]||0)+(aero[2]||0)),'vehicle');if(!p.vehicles[c.id])pay(price,`${c.brand} ${c.model}`);p.vehicles[c.id]={trim,upgrades,paint:a.paint,aero:a.aero,price};p.displayVehicle=c.id;message=`${c.brand} ${c.model} configuration saved.`}
 if(action==='equip'){const item=shop.find(x=>x.id===a.id);need(item&&owned(a.id));p.equipped[item.type]=item.id}
 if(action==='display-car'){need(p.vehicles[a.id]);p.displayVehicle=a.id}
 if(action==='wallpaper'){need(owned(a.id)&&p.configurations[a.id]&&['Emerald','Oxblood','Midnight','Ivory'].includes(a.wallpaper));p.configurations[a.id].wallpaper=a.wallpaper}
 if(action==='perk-buy'){need(p.owned.some(id=>phoneFamilies[id]||macbookFamilies[id]),'Purchase a Dorra OS device first.');p.perks??={owned:{},settings:{}};const perk=dorraPerkCatalog.find(x=>x.id===a.id);need(perk&&!p.perks.owned[perk.id]&&(!perk.requires||p.perks.owned[perk.requires]));pay(perk.price,perk.name);p.perks.owned[perk.id]={purchasedAt:now,price:perk.price};if(perk.id==='market-accelerator')p.perks.settings.marketRate='fast';message=`${perk.name} unlocked.`}
 if(action==='perk-setting'){need(p.perks?.owned?.['market-accelerator']&&dorraMarketRates[a.rate]);p.perks.settings.marketRate=a.rate}
 if(action==='app-buy'){need(p.owned.some(id=>phoneFamilies[id]||macbookFamilies[id]),'Purchase a Dorra OS device first.');p.osApps??={owned:{}};const app=dorraOsStoreCatalog.find(x=>x.id===a.id);need(app&&!app.coming);if(!p.osApps.owned[app.id]){pay(app.price,app.name);p.osApps.owned[app.id]={purchasedAt:now,price:app.price}}message=`${app.name} installed.`}
 return {message};}
function reduceMarket(s,h,action,a,now){
 need(['market-tick','market-trade','market-order','market-cancel','market-clear','market-settings','pocket-tick','pocket-trade'].includes(action),'Unknown market action.');
 const pocket=action.startsWith('pocket-'),premium=s.progress.osApps?.owned;need(premium?.[pocket?'pocket':'markets']||(action==='market-tick'&&premium?.bloomberg),'Purchase this investing app first.');
 if(h.market)s.progress.market=structuredClone(h.market);const engine=createMarketEngine(s,now),m=pocket?engine.ensurePocketMarket():engine.ensureDorraMarket();let message='Market saved.';
 if(action==='market-tick'||action==='pocket-tick'){const key=pocket?'pocketTickAt':'marketTickAt',rate=s.progress.perks?.settings?.marketRate||'normal',delay=pocket?2000:Math.max(2000,dorraMarketRates[rate]?.ms||12000);need(now-(h[key]||0)>=delay,'The next market tick is not ready yet.');h[key]=now;pocket?engine.pocketTick():engine.dorraMarketTick(false);message='Market updated.'}
 if(action==='market-trade'||action==='pocket-trade'||action==='market-order'){const companies=pocket?pocketCompanies:dorraMarketCompanies,c=companies.find(x=>x.symbol===a.symbol);need(c&&['buy','sell'].includes(a.side));const qty=whole(a.qty,pocket?100:1,pocket?100000:999);if(pocket)need(qty%100===0,'Pocket orders use increments of 100 shares.');const q=m.quotes[a.symbol],holding=m.holdings[a.symbol]||{shares:0,avg:0};
  if(action==='market-order'){need(['limit','stop','stop-limit','take-profit'].includes(a.type)&&['day','gtc'].includes(a.tif));const lim=['limit','stop-limit','take-profit'].includes(a.type)?Number(a.limit):undefined,stop=['stop','stop-limit'].includes(a.type)?Number(a.stop):undefined;need((lim===undefined||Number.isFinite(lim)&&lim>=1&&lim<=1e9)&&(stop===undefined||Number.isFinite(stop)&&stop>=1&&stop<=1e9));const reserved=engine.marketReservations(),estimate=qty*(lim||stop||q.price)*1.001;need(a.side==='buy'?s.balance-reserved.cash>=estimate:holding.shares-(reserved.shares[a.symbol]||0)>=qty,'Funds or shares are reserved or unavailable.');need(m.orders.filter(o=>o.status==='open').length<30,'Cancel an open order before placing another.');m.orders.push({id:crypto.randomUUID(),symbol:a.symbol,side:a.side,qty,type:a.type,limit:lim,stop,tif:a.tif,status:'open',placedTick:m.tick,at:now});message='Order placed.'}
  else{if(!pocket){need(engine.marketSession().id==='regular'&&!(m.halts[a.symbol]>m.tick),'This market is closed or halted.')}const reserved=pocket?{cash:0,shares:{}}:engine.marketReservations(),fill=pocket?q.price:q.price+(a.side==='buy'?engine.marketSpread(c)/2:-engine.marketSpread(c)/2),fee=pocket?0:Math.max(1,qty*fill*.001),total=Math[a.side==='buy'?'ceil':'floor'](Number((a.side==='buy'?qty*fill+fee:qty*fill-fee).toFixed(2)));if(a.side==='buy'){need(s.balance-reserved.cash>=total,'Not enough buying power.');holding.avg=(holding.shares*holding.avg+total)/(holding.shares+qty);holding.shares+=qty;m.holdings[a.symbol]=holding;s.balance-=total}else{need(holding.shares-(reserved.shares[a.symbol]||0)>=qty,'Not enough available shares.');holding.shares-=qty;s.balance+=total;if(!pocket)m.realisedPnl+=qty*(fill-holding.avg)-fee;if(holding.shares)m.holdings[a.symbol]=holding;else delete m.holdings[a.symbol]}m.trades.unshift({side:a.side,symbol:a.symbol,qty,price:Number(fill.toFixed(3)),fee:Number(fee.toFixed(2)),total,at:now,type:'market'});m.trades=m.trades.slice(0,pocket?30:40);message='Trade completed.'}
 }
 if(action==='market-cancel'){const order=m.orders.find(o=>o.id===a.id);need(order?.status==='open');order.status='cancelled';message='Order cancelled.'}
 if(action==='market-clear')m.trades=[];
 if(action==='market-settings'){const current=m.ui||{};const allowed={tab:['watchlist','portfolio','orders','news','risk','settings'],range:['1D','1W','1M','ALL'],sort:['symbol','change'],selected:dorraMarketCompanies.map(c=>c.symbol),chartTheme:['emerald','terminal','gold','violet','mono','custom']};for(const key of Object.keys(allowed))if(a[key]!==undefined){need(allowed[key].includes(a[key]));current[key]=a[key]}if(a.search!==undefined)current.search=String(a.search).replace(/[<>"'&\u0000-\u001f]/g,'').slice(0,40);if(a.chartCustom){current.chartCustom={};for(const key of ['line','up','down'])if(a.chartCustom[key]!==undefined){need(/^#[0-9a-fA-F]{6}$/.test(a.chartCustom[key]));current.chartCustom[key]=a.chartCustom[key]}}m.ui=current;}
 m.trades=m.trades.slice(0,pocket?30:40);if(!pocket){h.market=structuredClone(m);s.progress.market=structuredClone(m);if(!premium?.bloomberg)s.progress.market.events=s.progress.market.events.map(event=>event.applied?event:{id:event.id,symbol:event.symbol,headline:'Company catalyst scheduled',impactTick:event.impactTick,applied:false,status:'scheduled',category:event.category,sourceStatus:'unavailable'});}
 return {message};
}
