import {createVaultClient} from '../vault-client.js';
import {createAirportRenderer} from './renderer.mjs';
import {createAirportDashboard} from './dashboard.mjs';
import {GATEWAY_ID,GATEWAY_PRECINCTS,gatewayPlot} from './queensland-gateway-data.mjs';
import {AIRCRAFT_MODELS} from './aircraft-models.mjs';
import {equipmentFleetMarkup} from './ground-equipment-ui.mjs';
import {AIRCRAFT_CLASSES, BUILDINGS, SURFACES, RUNWAY_LENGTHS} from './catalog.mjs';

const $=selector=>document.querySelector(selector);
const POLL_INTERVAL_MS=30_000;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const number=value=>Number.isFinite(Number(value))?Number(value):0;
const list=value=>Array.isArray(value)?value:[];
const compact=value=>{const n=number(value);return n>=1e12?`${(n/1e12).toFixed(2)}T`:n>=1e9?`${(n/1e9).toFixed(2)}B`:n>=1e6?`${(n/1e6).toFixed(2)}M`:n>=1e4?`${(n/1e3).toFixed(1)}K`:Math.floor(n).toLocaleString('en-AU')};
const exact=value=>Math.floor(number(value)).toLocaleString('en-AU');
const duration=value=>{let seconds=Math.max(0,Math.ceil(number(value)/1000));if(seconds>=86400)return `${Math.floor(seconds/86400)}d ${Math.floor(seconds%86400/3600)}h`;if(seconds>=3600)return `${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;return seconds>=60?`${Math.floor(seconds/60)}m ${seconds%60}s`:`${seconds}s`};
const symbols={runwaySurface:'▰',runwayLength:'↔',taxiway:'⌘',terminal:'▥',tower:'♜',handling:'▰',researchLab:'⚗',cargo:'▤'};
const classInfo=size=>AIRCRAFT_CLASSES.find(item=>item.size===Number(size))||AIRCRAFT_CLASSES[0];
const aircraftArtCache=new Map(),aircraftImageCache=new Map();
// Generated by build-aircraft-previews.mjs from the shared map renderer. Avoid
// constructing cold high-detail meshes synchronously when opening the fleet.
const aircraftArt=id=>{if(aircraftArtCache.has(id))return aircraftArtCache.get(id);const m=AIRCRAFT_MODELS[id];if(!m)return '';const image=new Image();image.decoding='async';image.src=new URL(`./previews/${id}.png`,import.meta.url).href;aircraftImageCache.set(id,image);image.decode?.().catch(()=>{});const art=`<img data-aircraft-model="${esc(id)}" src="${esc(image.src)}" alt="${esc(m.name)}" style="display:block;width:100%;height:72px;max-width:180px;object-fit:contain">`;aircraftArtCache.set(id,art);return art};
const aircraftDimensions=id=>{const m=AIRCRAFT_MODELS[id];return m?`<p class="help-copy aircraft-dimensions" data-aircraft-dimensions="${esc(id)}" title="${esc(m.name)}">${m.length} m long · ${m.wingspan} m wingspan</p>`:''};
let vault,view,renderer,busy=false,dialog=null,inspector=null,priorFocus=null,pollTimer,clockTimer,toastTimer,disposed=false,pollPending=null;
let boostMultiplier=2,boostDuration=15,fleetFilter='all',serverClockOffset=0;
let equipmentRear=false;
const plotSizes=new Map();
const airport=()=>view?.selectedAirport||list(view?.airports).find(item=>item.id===view?.selectedAirportId);
const now=()=>Date.now()+serverClockOffset;
const dashboard=createAirportDashboard($('#airportDashboard'));

function showDashboard(){
  closeDialog();closeInspector();
  $('#airportDashboard').hidden=false;$('#airportHud').hidden=true;$('#airportCanvas').inert=true;
  dashboard.render(view);$('#dashboardTitle').focus({preventScroll:true});
}
function enterAirport(){
  closeDialog();closeInspector();
  if(!renderer)renderer=createAirportRenderer($('#airportCanvas'),{onSelect:selectInspector});
  renderer.setView(airport(),view);
  $('#airportDashboard').hidden=true;$('#airportHud').hidden=false;$('#airportCanvas').inert=false;
  $('#airportCanvas').focus({preventScroll:true});
}

function warmFleetArt(){
  const ids=Object.keys(AIRCRAFT_MODELS);const schedule=callback=>'requestIdleCallback' in window?requestIdleCallback(callback,{timeout:1200}):setTimeout(callback,80);
  const next=()=>{if(disposed||!ids.length)return;aircraftArt(ids.shift());if(ids.length)schedule(next)};schedule(next);
}
function toast(message,error=false){const element=$('#airportToast');clearTimeout(toastTimer);element.textContent=message;element.className=`airport-toast show${error?' error':''}`;toastTimer=setTimeout(()=>{element.className='airport-toast'},5000)}
function saveStatus(status,error){dashboard.status(status);const element=$('#airportSaveStatus');element.className=`save-indicator${status==='error'?' error':''}`;element.innerHTML=`<i></i> ${status==='saving'?'Saving your airport…':status==='error'?'Connection interrupted':'Saved to cloud'}`;if(status==='error'&&error)toast(error.message||'Your save could not be updated.',true)}
function applyResult(result){
  if(!result?.view)throw new Error('The cloud service returned an incomplete airport update.');
  view=result.view;if(view.serverNow)serverClockOffset=number(view.serverNow)-Date.now();
  renderHud();dashboard.render(view);renderer?.setView(airport(),view);if(inspector)renderInspector();
}
async function runCommand(command,success){
  if(busy||!view)return;busy=true;saveStatus('saving');
  try{await pollPending;const result=await vault.airportCommand({requestId:crypto.randomUUID(),expectedRevision:view.revision,command});applyResult(result);saveStatus('saved');if(dialog)renderDialog();if(success)toast(success);return result}
  catch(error){saveStatus('error');toast(error?.message||'This action could not be completed.',true);try{applyResult(await vault.airportLoad())}catch{}}
  finally{busy=false}
}
async function poll(){
  if(busy||pollPending||disposed||!vault||document.hidden)return;
  pollPending=(async()=>{try{applyResult(await vault.airportLoad());if(dialog&&dialog!=='idle'&&dialog!=='help')renderDialog(true);saveStatus('saved')}catch(error){saveStatus('error');$('#flightTicker').innerHTML='<span class="live-dot"></span><span>Showing saved operations · reconnecting to the cloud</span>';if(['SESSION_REPLACED','AUTH_REQUIRED','UNAUTHORIZED','SESSION_EXPIRED','AUTH_SESSION_ENDED','ACCOUNT_DISABLED'].includes(error.code))fatal(error)}})();
  try{await pollPending}finally{pollPending=null}
}
function renderHud(){
  const a=airport();if(!a)return;
  $('#cashBalance').textContent=compact(a.cash);$('#cashBalance').parentElement.title=`${exact(a.cash)} airport cash`;
  $('#diamondBalance').textContent=compact(view.diamonds);$('#researchBalance').textContent=compact(a.research);
  $('#airportHud').dataset.airportId=a.id;
  $('#airportName').textContent=a.name;$('#airportRegion').textContent=`${a.region||'Queensland'}, Australia`.toUpperCase();
  $('#airportTier').textContent=`${classInfo(a.maxSize).label} · ${a.code||''}`;
  const levels=list(a.buildings).reduce((sum,b)=>sum+number(b.level),0),max=list(a.buildings).reduce((sum,b)=>sum+number(b.maxLevel),0);
  $('#airportProgress').style.width=`${Math.max(6,max?levels/max*100:6)}%`;
  $('#airportRate').textContent=`$${compact(number(a.rates?.cashPerHour)/60)}`;
  $('#airportTraffic').textContent=`${list(a.gates).length} gate${list(a.gates).length===1?'':'s'} · ${exact(number(a.rates?.departuresPerHour))} flights/h`;
  $('#milestoneDot').hidden=!list(a.milestones).some(item=>item.canClaim);
  const activePlanes=[...new Map(list(a.gates).map(g=>g.currentAircraft||g.aircraft).filter(Boolean).map(plane=>[plane.id,plane])).values()];
  const trafficLabel=activePlanes.length>1?`${activePlanes.length} aircraft types on the apron`:activePlanes[0]?`${activePlanes[0].name} services active`:'Upgrade your airport to welcome more aircraft';
  $('#flightTicker').innerHTML=`<span class="live-dot"></span><span>${esc(trafficLabel)} · ${exact(a.stats?.departures)} departures</span>`;
  const boost=$('#boostActive');boost.hidden=!a.boost;if(a.boost){boost.innerHTML=`ϟ ${a.boost.multiplier}× income boost<small data-countdown="${a.boost.endsAt}">${duration(a.boost.endsAt-now())} remaining</small>`}
}
function quoteText(quote={}){return `${number(quote.cashCost)?`$${compact(quote.cashCost)}`:''}${number(quote.researchCost)?`${number(quote.cashCost)?' + ':''}${compact(quote.researchCost)} RP`:''}`||'Free'}
function quoteAvailability(quote={}){return quote.available!==false&&quote.affordable!==false}
function quoteButtons(quote,action,data={},label='Upgrade'){
  if(!quote)return '<span class="status-chip">Maximum level</span>';
  if(quote.maxed)return `<span class="status-chip">Maximum for this location</span>${quote.reason?`<p class="help-copy">${esc(quote.reason)}</p>`:''}`;
  const attributes=Object.entries(data).map(([key,value])=>`data-${key}="${esc(value)}"`).join(' ');
  const blocked=quote.available===false;
  return `<button class="primary-button" data-action="${action}" ${attributes} ${quoteAvailability(quote)?'':'disabled'}>${esc(label)} <span class="button-cost">${quoteText(quote)}</span></button>${number(quote.diamondCost)>0&&!blocked?`<button class="diamond-button" data-action="${action}" ${attributes} data-use-diamonds="true" ${number(view.diamonds)>=number(quote.diamondCost)?'':'disabled'}>Use diamonds · ◆ ${exact(quote.diamondCost)}</button>`:''}${quote.reason?`<p class="help-copy">${esc(quote.reason)}</p>`:''}`;
}
function pips(level,max=5){return `<div class="level-pips" aria-label="Level ${level} of ${max}">${Array.from({length:Math.min(max,13)},(_,i)=>`<i class="${i<level?'filled':''}"></i>`).join('')}</div>`}
function plotControls(plot){
  const sizes=list(plot.sizeQuotes),size=plotSizes.get(`${airport().id}:${plot.id}`)||0,selected=sizes.find(item=>item.size===size);
  return `${sizes.length>1?`<label class="form-field">Opening aircraft size<select data-plot-size="${esc(plot.id)}">${sizes.map(item=>`<option value="${item.size}" ${item.size===size?'selected':''}>${esc(item.name)} · ${quoteText(item.quote)}</option>`).join('')}</select></label>`:'<div class="metric-pair"><span>Opening size</span><b>Light aircraft</b></div>'}${quoteButtons(selected?.quote||plot.quote,'build-gate',{'plot-id':plot.id,'size':size},plot.bay?'Purchase bay':'Build gate')}${plot.bay?`<p class="help-copy">${esc(plot.bay.precinct)} · ${esc(plot.bay.referenceCapacity)} envelope. ${plot.bay.conflicts.length?'Shared pavement: conflicting bays cannot operate together. You can switch the active configuration after purchase.':'A separate operating position.'}</p>`:''}`;
}
function selectInspector(selection){inspector=selection;renderer?.setSelected(selection);renderInspector()}
function closeInspector(){inspector=null;renderer?.setSelected(null);$('#buildInspector').hidden=true}
function renderInspector(){
  const a=airport();if(!a||!inspector)return;let content='';
  if(inspector.kind==='building'){
    const b=list(a.buildings).find(item=>item.key===inspector.id);if(!b)return closeInspector();const def=BUILDINGS.find(item=>item.key===b.key);
    const task=list(a.constructions).find(item=>item.building===b.key||item.buildingKey===b.key||item.targetId===b.key||item.id===b.upgrading?.id);
    content=`<div class="inspector-art" aria-hidden="true">${symbols[b.key]||'▥'}</div><p class="eyebrow">AIRPORT INFRASTRUCTURE</p><h2 id="inspectorTitle">${esc(b.name||b.label)}</h2><p>${esc(def?.description||'Develop your airport to handle more flights.')}</p>${pips(b.level,b.maxLevel)}<div class="metric-pair"><span>Current</span><b>${esc(b.currentLabel||`Level ${b.level}`)}</b></div>${b.quote?`<div class="metric-pair"><span>Next upgrade</span><b>${esc(b.quote.nextLabel||`Level ${b.quote.nextLevel}`)}</b></div>`:''}${task?taskMarkup(task):b.upgrading?'<p>Construction is underway. Open Build to see its progress.</p>':quoteButtons(b.quote,'upgrade',{'building':b.key})}${b.quote?.durationMs?`<p class="help-copy">◷ ${duration(b.quote.durationMs)} construction · airport stays open</p>`:''}`;
  }else if(inspector.kind==='gate'){
    const gate=list(a.gates).find(g=>g.id===inspector.id);if(!gate)return closeInspector();
    content=`<div class="inspector-art">${aircraftArt(gate.currentAircraft?.id||gate.aircraft?.id)}</div><p class="eyebrow">AIRCRAFT STAND</p><h2 id="inspectorTitle">${esc(gate.label||gate.id)}</h2><p>Each gate hosts one aircraft at a time. Larger stands open the door to larger arrivals.</p>${pips(gate.size+1,6)}<div class="metric-pair"><span>Aircraft size</span><b>${esc(classInfo(gate.size).name)}</b></div><div class="metric-pair"><span>Plot limit</span><b>${esc(classInfo(gate.maxSize??a.maxSize).name)}</b></div>${quoteButtons(gate.quote,'upgrade-gate',{'gate-id':gate.id},'Expand gate')}${bayOperation(gate)}`;
  }else{
    const plot=list(a.gatePlots).find(item=>item.id===inspector.id);if(!plot)return closeInspector();
    content=`<div class="inspector-art" aria-hidden="true">＋</div><p class="eyebrow">${plot.bay?esc(plot.bay.precinct):'ROOM TO GROW'}</p><h2 id="inspectorTitle">${plot.bay?esc(plot.label):'New aircraft gate'}</h2><p>${plot.bay?'Purchase this existing bay to add operating capacity. The apron and parking position are already in place.':'Add another working stand. Your ground crew automatically handles every eligible arrival.'}</p><div class="metric-pair"><span>Plot capacity</span><b>${esc(classInfo(plot.maxSize??a.maxSize).name)}</b></div>${plotControls(plot)}`;
  }
  if(inspector.kind==='building'&&inspector.id==='handling')content+='<button class="secondary-button" data-action="ground-fleet">View ground fleet →</button>';
  $('#buildInspector').hidden=false;$('#buildInspector').innerHTML=`<button class="inspector-close" data-action="close-inspector" aria-label="Close building inspector">×</button>${content}`;
}
function taskMarkup(task){const end=number(task.endsAt),remaining=Math.max(0,end-now());return `<div class="metric-pair"><span>Under construction</span><b data-countdown="${end}">${duration(remaining)}</b></div><div class="task-progress"><i style="width:${Math.min(100,number(task.progress)*(number(task.progress)<=1?100:1))}%"></i></div><button class="diamond-button" data-action="skip-task" data-task-id="${esc(task.id)}" ${number(view.diamonds)>=number(task.skipDiamonds)?'':'disabled'}>Finish now · ◆ ${exact(task.skipDiamonds)}</button>`}
function openDialog(type){dialog=type;priorFocus=document.activeElement;$('#airportDialog').hidden=false;renderDialog();$('.dialog-card').focus();closeInspector()}
function closeDialog(){dialog=null;$('#airportDialog').hidden=true;if(priorFocus?.isConnected)priorFocus.focus()}
function renderDialog(preserveInput=false){
  if(!dialog)return;const body=$('#dialogBody'),scroll=body.scrollTop,active=document.activeElement;
  const focusInfo=preserveInput&&body.contains(active)?{id:active.id,tag:active.tagName,dataset:{...active.dataset},selectionStart:active.selectionStart,selectionEnd:active.selectionEnd}:null;
  const formValues=preserveInput?[...body.querySelectorAll('input[id],select[id]')].map(input=>({id:input.id,value:input.value})):[];
  const openBayAreas=[...body.querySelectorAll('details[data-bay-area][open]')].map(d=>d.dataset.bayArea);
  let title='',eyebrow='AIRPORT OPERATIONS',html='';
  if(dialog==='buildings'){title='Make room for more';eyebrow='BUILD & EXPAND';html=buildingsMarkup()}
  else if(dialog==='fleet'){title='A world of aircraft';eyebrow='YOUR ARRIVALS BOARD';html=fleetMarkup()}
  else if(dialog==='ground-fleet'){title='Meet your ground fleet';eyebrow='APRON OPERATIONS';html=equipmentFleetMarkup(airport(),equipmentRear)}
  else if(dialog==='research'){title='A smarter airport';eyebrow='RESEARCH & DEVELOPMENT';html=researchMarkup()}
  else if(dialog==='network'){title='Your Australian adventure';eyebrow='AIRPORT NETWORK';html=networkMarkup()}
  else if(dialog==='milestones'){title='Every flight counts';eyebrow='CAREER MILESTONES';html=milestonesMarkup()}
  else if(dialog==='boost'){title='Give your airport a lift';eyebrow='DIAMOND BOOSTS';html=boostMarkup()}
  else if(dialog==='withdraw'){title='Send your profits home';eyebrow='DORRA HOUSE TRANSFER';html=withdrawMarkup()}
  else if(dialog==='idle'){title='Welcome back, airport owner';eyebrow='YOUR AIRPORTS KEPT WORKING';html=idleMarkup()}
  else{title='Ready for take-off?';eyebrow='A LITTLE HELP FROM THE TOWER';html=helpMarkup()}
  $('#dialogTitle').textContent=title;$('#dialogEyebrow').textContent=eyebrow;body.innerHTML=html;
  for(const d of body.querySelectorAll('details[data-bay-area]'))d.open=openBayAreas.includes(d.dataset.bayArea);
  for(const input of formValues){const element=document.getElementById(input.id);if(element)element.value=input.value}
  if(preserveInput&&dialog==='withdraw')updateWithdrawPreview();
  if(focusInfo){const candidate=focusInfo.id?document.getElementById(focusInfo.id):[...body.querySelectorAll(focusInfo.tag.toLowerCase())].find(element=>Object.entries(focusInfo.dataset).every(([key,value])=>element.dataset[key]===value));candidate?.focus({preventScroll:true});if(candidate&&focusInfo.selectionStart!=null)try{candidate.setSelectionRange(focusInfo.selectionStart,focusInfo.selectionEnd)}catch{}}
  body.scrollTop=scroll;
}
function brisbaneBayList(a){return `<p class="dialog-lead">Purchase each existing bay individually. Overlapping alternatives share operating space. The remote oversize cargo reservation also keeps neighbouring bays clear.</p>${['Domestic','International','General aviation','North remote / taxiway parking','Logistics / Airport South'].map(area=>{const plots=a.gatePlots.filter(p=>p.bay?.precinct===area&&!p.occupied);return `<details data-bay-area="${esc(area)}"><summary class="section-label">${esc(area)} · ${plots.length} bays to purchase</summary><div class="dialog-grid">${plots.map(p=>`<article class="operation-card"><h3>${esc(p.label)}</h3><p>${p.bay.contact?'Terminal contact position':p.bay.area==='north'&&/^R[1-8]/.test(p.bay.bay)?'Former 14/32 runway parking · Closed to takeoff and landing':'Remote / apron position'}${p.bay.oversizeReservation?' · Oversize cargo reserves neighbouring space':''}</p>${plotControls(p)}</article>`).join('')}</div></details>`}).join('')}`}
function bayOperation(g){return g.bay?`<p class="help-copy">${esc(g.bay.precinct)} · ${g.active?'Operating space active':'Operating space inactive'}</p><button class="secondary-button" data-action="set-gate-active" data-gate-id="${esc(g.id)}" data-active="${!g.active}">${g.active?'Pause bay':'Activate bay'}</button>${!g.active&&g.bay.conflicts.length?'<p class="help-copy">Activating this bay pauses any owned bays that share its parking envelope.</p>':''}`:''}
function gatewayStandList(a){return `<p class="dialog-lead">Tidal Ribbon connects six double-sided concourses through one flowing glass-roofed terminal. Two staggered banks of three 4,500 m runways share taxiways around their ends, with a covered airport rail station and one arrival hall. Upgrade operating certification to welcome larger aircraft. All 192 stands have their own parking space.</p>${GATEWAY_PRECINCTS.map(precinct=>{const plots=a.gatePlots.filter(p=>gatewayPlot(p.id)?.precinct.id===precinct.id&&!p.occupied);return `<details data-bay-area="${precinct.id}"><summary class="section-label">${esc(precinct.name)} · ${plots.length} stands available</summary><p class="help-copy">${esc(precinct.role)} · Runway ${precinct.designators.join(" / ")}</p><div class="dialog-grid">${plots.map(p=>`<article class="operation-card"><h3>${esc(p.label)}</h3><p>Dedicated stand · supports super-heavy aircraft after upgrades.</p>${plotControls(p)}</article>`).join("")}</div></details>`}).join("")}`}
function buildingsMarkup(){const a=airport();return `<p class="dialog-lead">Start with the runway and a few gates. Every upgrade changes what your airport can handle. Buildings keep working while your next improvement is under construction.</p>${list(a.constructions).length?`<h3 class="section-label">Construction underway</h3><div class="dialog-grid">${a.constructions.map(task=>`<article class="operation-card"><h3>${esc(task.label)}</h3>${taskMarkup(task)}</article>`).join('')}</div>`:''}<h3 class="section-label">Infrastructure</h3><button class="secondary-button" data-action="ground-fleet">View ground fleet →</button><div class="dialog-grid">${list(a.buildings).map(b=>`<article class="operation-card"><div class="card-header"><span class="card-symbol">${symbols[b.key]||'▥'}</span><span class="status-chip">Lv. ${b.level} / ${b.maxLevel}</span></div><h3>${esc(b.name||b.label)}</h3><p>${esc(b.description||BUILDINGS.find(item=>item.key===b.key)?.description)}</p><div class="metric-pair"><span>In operation</span><b>${esc(b.currentLabel||`Level ${b.level}`)}</b></div>${b.upgrading?'<span class="status-chip gold">Construction underway</span>':quoteButtons(b.quote,'upgrade',{'building':b.key},b.quote?.nextLabel||'Upgrade')}</article>`).join('')}</div>${a.id==='gold-coast'?'<p class="dialog-lead">Gold Coast has 28 terminal position labels on shared MARS bays: up to 19 narrowbodies, or up to 7 widebodies and 1 narrowbody. Remote 30 accommodates 2 narrowbodies or 1 widebody. GA G1 has an 18 m wingspan limit. The northern GA apron provides shared light-aircraft parking; its total capacity varies. Three helicopter positions, H1–H3, are separate from the fixed-wing bay purchases.</p>':''}<h3 class="section-label">Gates & expansion plots</h3><div class="dialog-grid">${list(a.gates).map(g=>`<article class="operation-card"><span class="card-symbol">✈</span><h3>${esc(g.label||g.id)}</h3><p>${esc(classInfo(g.size).name)} aircraft · plot supports ${esc(classInfo(g.maxSize??a.maxSize).name)}</p>${quoteButtons(g.quote,'upgrade-gate',{'gate-id':g.id},'Expand gate')}${bayOperation(g)}</article>`).join('')}${['brisbane',GATEWAY_ID].includes(a.id)?'':list(a.gatePlots).filter(p=>!p.occupied).map((p,i)=>`<article class="operation-card"><span class="card-symbol">＋</span><h3>${esc(p.bay?p.label:`Expansion plot ${i+1}`)}</h3><p>${p.bay?esc(p.bay.precinct)+' · Existing parking space. Purchase operating rights, then upgrade service equipment.':`Open a light-aircraft stand, then expand up to ${esc(classInfo(p.maxSize??a.maxSize).name)}.`}</p>${plotControls(p)}</article>`).join('')}</div>${a.id==='brisbane'?brisbaneBayList(a):a.id===GATEWAY_ID?gatewayStandList(a):''}`}
function fleetMarkup(){const a=airport(),planes=list(a.aircraftRequirements);return `<p class="dialog-lead">Aircraft arrive automatically when your runway, taxiways, gates, ground equipment and research meet their requirements. These are simplified game requirements for your airport network.</p><div class="segmented-control" aria-label="Filter aircraft">${[['all','All aircraft'],['eligible','Flying now'],['locked','Next arrivals']].map(([id,label])=>`<button class="${fleetFilter===id?'active':''}" data-action="fleet-filter" data-filter="${id}">${label}</button>`).join('')}</div><div class="dialog-grid three">${planes.filter(p=>fleetFilter==='all'||(fleetFilter==='eligible'?p.eligible:!p.eligible)).map(plane=>`<article class="operation-card fleet-card ${plane.eligible?'':'locked'}"><div class="aircraft-art">${aircraftArt(plane.id)}</div><span class="aircraft-class">${esc(classInfo(plane.size).name).toUpperCase()}</span><h3>${esc(plane.name)}</h3>${aircraftDimensions(plane.id)}<span class="status-chip ${plane.eligible?'':'locked'}">${plane.eligible?'● Flying now':'Requirements pending'}</span><div class="metric-pair"><span>Per departure</span><b>$${compact(plane.income)}</b></div><ul class="requirements"><li>${exact(plane.runwayLength)} m runway · ${esc(SURFACES.find(s=>s.level===plane.surface)?.shortName||'pavement')}</li>${list(plane.missing).slice(0,7).map(text=>`<li class="unmet">○ ${esc(text)}</li>`).join('')}${plane.eligible?'<li class="met">✓ All requirements met</li>':''}</ul>${plane.special?`<p>${esc(plane.special)}</p>`:''}</article>`).join('')||'<p class="empty-state">No aircraft in this view yet.</p>'}</div>`}
function researchMarkup(){const a=airport();return `<p class="dialog-lead">Research points belong to ${esc(a.name)}. Improve turnaround, passenger revenue and certifications to welcome the next aircraft class.</p><div class="currency-summary"><div><small>RESEARCH AVAILABLE</small><strong>⚗ ${exact(a.research)}</strong></div><div><small>POINTS PER HOUR</small><strong>${compact(a.rates?.researchPerHour)}</strong></div></div><div class="dialog-grid">${list(a.researchProjects).map(project=>`<article class="operation-card"><div class="card-header"><span class="card-symbol">${project.id.includes('operations')?'✈':'⚗'}</span>${project.completed?'<span class="status-chip">✓ Researched</span>':project.active?'<span class="status-chip gold">In progress</span>':''}</div><h3>${esc(project.name)}</h3><p>${esc(project.description)}</p>${project.completed?'<p class="help-copy">This improvement is active at this airport.</p>':project.active?taskMarkup(list(a.constructions).find(t=>t.researchId===project.id||t.targetId===project.id)||{id:project.active.id||project.id,endsAt:project.active.endsAt||now(),skipDiamonds:project.active.skipDiamonds||0}):quoteButtons(project.quote,'research',{'research-id':project.id},'Research')}</article>`).join('')}</div>`}
function networkMarkup(){return `<p class="dialog-lead">From a coastal flying club to Brisbane’s biggest aircraft. Every airport you own keeps earning. Cash and research stay at each location; diamonds travel with you.</p>${list(view.airports).map(a=>{const unlock=a.unlock||{};const selected=a.id===view.selectedAirportId;return `<article class="network-card ${a.owned?'':'locked'}"><div class="airport-stamp" aria-hidden="true">${a.owned?'✈':'⌖'}</div><div><span class="airport-tag">${esc(a.region)}${a.fictional?' · FICTIONAL AIRPORT':''}</span><h3>${esc(a.name)}</h3><p>${esc(classInfo(a.maxSize).name)} maximum · ${exact(a.maxRunwayLength)} m · ${a.demand}× demand${a.owned?`<br>$${compact(a.cash)} cash · ${compact(a.research)} research`:''}</p>${!a.owned&&list(unlock.requirements).length?`<ul class="requirements">${unlock.requirements.map(r=>`<li class="${r.met?'met':'unmet'}">${r.met?'✓':'○'} ${esc(r.label)}${r.target?` · ${typeof r.current==='number'?compact(r.current):esc(r.current)} / ${compact(r.target)}`:''}</li>`).join('')}</ul>`:''}</div><div class="network-actions">${selected?'<span class="selected-marker">● You are here</span>':a.owned?`<button class="primary-button" data-action="select-airport" data-airport-id="${esc(a.id)}">Visit airport →</button>`:`<button class="primary-button" data-action="unlock-airport" data-airport-id="${esc(a.id)}" ${unlock.canUnlock&&unlock.affordable!==false?'':'disabled'}>Open · $${compact(unlock.cashCost)}</button>${number(unlock.diamondCost)?`<button class="diamond-button" data-action="unlock-airport" data-airport-id="${esc(a.id)}" data-use-diamonds="true" ${unlock.canUnlockWithDiamonds?'':'disabled'}>Open early · ◆ ${exact(unlock.diamondCost)}</button>`:''}`}</div></article>`}).join('')}<p class="help-copy">Airport capacities and expansion limits are game design choices. Named airports are not operational airport plans.</p>`}
function milestonesMarkup(){return `<p class="dialog-lead">Build, expand and keep flights moving. Claim airport milestones for cash, research and plane diamonds. Rare diamond drops are also awarded automatically on eligible departures.</p>${list(airport().milestones).map(m=>`<article class="milestone-row"><span class="milestone-star" aria-hidden="true">${m.claimed?'✓':'★'}</span><div><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p><div class="task-progress"><i style="width:${clampPercent(number(m.current)/Math.max(1,number(m.target))*100)}%"></i></div><p>${compact(m.current)} / ${compact(m.target)}${m.claimed?' · Reward collected':''}</p><p class="milestone-all-rewards">Rewards: ${compact(m.reward?.cash)} cash · ${compact(m.reward?.research)} RP · ◆ ${compact(m.reward?.diamonds)}</p></div><div class="milestone-reward">${number(m.reward?.diamonds)?`◆ ${exact(m.reward.diamonds)}`:number(m.reward?.cash)?`$${compact(m.reward.cash)}`:`⚗ ${compact(m.reward?.research)}`}${m.canClaim?`<button class="primary-button" data-action="claim-milestone" data-milestone-id="${esc(m.id)}">Collect</button>`:''}</div></article>`).join('')||'<div class="empty-state"><span>★</span>Your next milestone is just a few flights away.</div>'}`}
const clampPercent=value=>Math.max(0,Math.min(100,value));
function boostPrice(){const match=list(view?.boostOptions).find(b=>b.multiplier===boostMultiplier&&b.durationMinutes===boostDuration);return number(match?.diamondCost??match?.cost??({5:5,15:12,30:20,60:35}[boostDuration]*({2:1,5:3,10:6}[boostMultiplier])))}
function boostMarkup(){const a=airport(),cost=boostPrice();return `<div class="boost-hero"><span aria-hidden="true">ϟ</span><h3>A little extra lift</h3><p>Multiply cash income at ${esc(a.name)}. Research, flight speed and diamond odds stay the same. Boost timers continue while you are away.</p></div>${a.boost?`<p class="dialog-lead" style="margin-top:16px">Your ${a.boost.multiplier}× boost is running for another <b data-countdown="${a.boost.endsAt}">${duration(a.boost.endsAt-now())}</b>.</p>`:''}<div class="boost-options" aria-label="Choose boost multiplier">${[2,5,10].map(value=>`<button class="boost-choice ${boostMultiplier===value?'active':''}" data-action="boost-multiplier" data-multiplier="${value}" aria-pressed="${boostMultiplier===value}"><strong>${value}×</strong><small>${value===2?'A LITTLE LIFT':value===5?'FULL THROTTLE':'SUPERCHARGED'}</small></button>`).join('')}</div><label class="form-field">Boost duration<select id="boostDuration">${[5,15,30,60].map(value=>`<option value="${value}" ${boostDuration===value?'selected':''}>${value} minutes</option>`).join('')}</select></label><div class="conversion-preview"><span>Your diamonds <strong>◆ ${exact(view.diamonds)}</strong></span><span>Boost price <strong>◆ ${cost}</strong></span></div><div class="form-actions"><button class="primary-button" data-action="activate-boost" ${view.diamonds>=cost&&!a.boost?'':'disabled'}>${a.boost?'Boost already active':`Activate ${boostMultiplier}× boost · ◆ ${cost}`}</button></div><p class="help-copy">Diamonds also finish construction, cover upgrade shortages and unlock your next airport early. Airport boosts do not stack.</p>`}
function withdrawMarkup(){const a=airport(),max=Math.floor(number(a.cash)/10)*10;return `<p class="dialog-lead">Turn airport profit into Dorra House money. Every 10 airport cash becomes 1 Dorra. Withdrawals use cash from ${esc(a.name)}.</p><div class="currency-summary"><div><small>AIRPORT CASH</small><strong>$${exact(a.cash)}</strong></div><div><small>DORRA HOUSE BALANCE</small><strong>$${exact(vault?.snapshot?.balance)}</strong></div></div><form id="withdrawForm"><label class="form-field">Airport cash to withdraw<input id="withdrawAmount" name="amountCash" type="number" min="10" max="${max}" step="10" value="${Math.min(max,100)}" inputmode="numeric" ${max<10?'disabled':''}><small>Use whole multiples of 10. Cash remains at your airport until the transfer succeeds.</small></label><div class="conversion-preview"><span>Airport cash <strong id="withdrawPreviewCash">$${exact(Math.min(max,100))}</strong></span><span>→</span><span>You receive <strong id="withdrawPreviewDorra">$${exact(Math.min(max,100)/10)} Dorra</strong></span></div><div class="form-actions"><button type="button" class="secondary-button" data-action="withdraw-max" ${max<10?'disabled':''}>Use maximum</button><button type="submit" class="primary-button" ${max<10?'disabled':''}>Transfer to Dorra House</button></div></form><p class="help-copy">Dorra money cannot be deposited into this game. Your airport earns its own cash, one departure at a time.</p>`}
let initialIdle=null;
function idleMarkup(){
  const result=initialIdle||{},earnings=result.earnings||{},locations=list(view?.airports);
  const entries=Array.isArray(earnings)?earnings.map((item,index)=>[item.airportId||item.id||`airport-${index+1}`,item]):Object.entries(earnings.byAirport||{});
  const rows=entries.filter(([,item])=>item&&typeof item==='object').map(([id,item])=>({id,name:locations.find(a=>a.id===id)?.name||item.name||id,cash:number(item.cash),research:number(item.research),diamonds:number(item.diamonds),departures:number(item.departures)}));
  const total=key=>typeof earnings[key]==='number'?number(earnings[key]):rows.reduce((sum,row)=>sum+row[key],0);
  const cash=total('cash'),research=total('research'),diamonds=total('diamonds'),departures=total('departures');
  const creditedMs=number(result.creditedMs)||Math.min(number(result.elapsedMs),24*60*60*1000);
  return `<p class="dialog-lead">You were away for ${duration(result.elapsedMs)}. Your airports completed <b>${exact(departures)} departures</b> and earned the amounts below${result.capped?` during the first ${duration(creditedMs)}. The 24-hour away earnings limit was reached`:''}.</p>
    <div class="idle-summary idle-summary-network"><div><small>AIRPORT CASH EARNED</small><strong data-idle-total="cash" data-value="${cash}">$${compact(cash)}</strong></div><div><small>LOCAL RESEARCH</small><strong data-idle-total="research" data-value="${research}">⚗ ${compact(research)}</strong></div><div class="idle-shared-diamonds"><small>SHARED DIAMONDS EARNED</small><strong data-idle-total="diamonds" data-value="${diamonds}">◆ ${compact(diamonds)}</strong></div></div>
    <h3 class="section-label">Earnings by airport</h3><p class="idle-ledger-note">Cash and research stay at the airport that earned them. Diamond drops are added to your shared diamond balance.</p>
    ${rows.length?`<div id="idleLedger" class="idle-ledger-scroll" role="region" aria-label="Away earnings by airport" tabindex="0"><table class="idle-ledger"><thead><tr><th scope="col">Airport</th><th scope="col">Local cash</th><th scope="col">Research</th><th scope="col">Diamonds</th><th scope="col">Departures</th></tr></thead><tbody>${rows.map(row=>`<tr data-idle-airport="${esc(row.id)}"><th scope="row">${esc(row.name)}</th><td data-idle-cash data-value="${row.cash}">$${exact(row.cash)}</td><td data-idle-research data-value="${row.research}">${exact(row.research)} RP</td><td data-idle-diamonds data-value="${row.diamonds}">◆ ${exact(row.diamonds)}</td><td data-idle-departures data-value="${row.departures}">${exact(row.departures)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state" data-idle-empty><span>✈</span>No airport departure earnings were recorded for this time away. Your existing airport balances are preserved.</div>'}
    <p class="dialog-lead idle-saved-note">These earnings are already saved. Your cash, research and shared diamonds are ready to use.</p><button class="primary-button" data-action="close-dialog">Back to the apron →</button>`;
}
function helpMarkup(){return `<dl class="help-list"><div><dt>01</dt><dd><b>Start small, keep it moving</b>Your first light-aircraft gate is already earning. Upgrade the runway, extend it and build extra gates to grow your traffic.</dd></div><div><dt>02</dt><dd><b>The right airport for the right aircraft</b>Planes need a suitable gate, runway length and surface, taxiways, equipment and certification. Open Aircraft to see exactly what each one needs.</dd></div><div><dt>03</dt><dd><b>Three currencies, one growing network</b>Cash buys infrastructure. Research improves operations. Plane diamonds buy temporary boosts, complete timers, cover shortages and open the next airport early.</dd></div><div><dt>04</dt><dd><b>Your airports keep working</b>All owned airports earn. Your cloud save catches up for up to 24 hours when you return. Sign in to the same account on any device to continue your airport network.</dd></div><div><dt>05</dt><dd><b>Send profits back to Dorra House</b>Withdraw 10 airport cash for 1 Dorra. Airport income is independent, so there are no Dorra deposits.</dd></div><div><dt>⌨</dt><dd><b>Play your way</b>Click buildings in the world or use Build for every keyboard-accessible upgrade. Drag the map to pan and scroll the mouse wheel to zoom. With the map focused, use arrow keys to pan, + / − to zoom and 0 to reset the view. Tab moves between controls; Escape closes a window. Reduced-motion preferences are respected automatically.</dd></div></dl><h3 class="section-label">Online game information</h3><p class="dialog-lead">An internet connection and your Dorra House account are required. Progress saves automatically after airport actions. Aircraft movements illustrate operations; the server calculates rewards, purchases and transfers. One gameplay session can be active for your account at a time. Airport sizes and aircraft requirements are simplified for gameplay.</p><p class="dialog-lead">Hamilton Island neighbourhood map data: © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a> (ODbL). Building appearance, gardens and boats are artistic approximations.</p><div class="form-actions"><button class="primary-button" data-action="close-dialog">Let’s build an airport</button><a class="secondary-button" href="index.html" data-return-house>Return to Dorra House ↗</a></div>`}
function updateClocks(){document.querySelectorAll('[data-countdown]').forEach(element=>{const remaining=number(element.dataset.countdown)-now();element.textContent=remaining>0?duration(remaining):'Finishing…'})}
function updateWithdrawPreview(){const amount=number($('#withdrawAmount')?.value);$('#withdrawPreviewCash').textContent=`$${exact(amount)}`;$('#withdrawPreviewDorra').textContent=`$${exact(amount/10)} Dorra`}
async function withdraw(event){
  event.preventDefault();if(busy)return;const amount=Number($('#withdrawAmount')?.value),a=airport();if(!Number.isSafeInteger(amount)||amount<10||amount%10||amount>number(a.cash)){toast('Enter a whole multiple of 10 within this airport’s cash balance.',true);return}
  busy=true;saveStatus('saving');try{await pollPending;const result=await vault.withdrawAirportCash({requestId:crypto.randomUUID(),airportId:a.id,amountCash:amount,expectedAirportRevision:view.revision});applyResult(result);saveStatus('saved');renderDialog();toast(`$${exact(amount/10)} sent to Dorra House.`)}catch(error){saveStatus('error');toast(error.message||'The withdrawal could not be completed.',true)}finally{busy=false}
}
async function returnHouse(event){event.preventDefault();if(busy){toast('Finishing the current airport action. Try again in a moment.');return}disposed=true;clearInterval(pollTimer);clearInterval(clockTimer);try{await pollPending;await vault?.flush?.();renderer?.dispose();vault?.close();location.href='index.html'}catch(error){disposed=false;pollTimer=setInterval(poll,POLL_INTERVAL_MS);clockTimer=setInterval(updateClocks,1000);toast(error.message||'Your save is still pending. Please try again.',true)}}
async function handleClick(event){
  const home=event.target.closest('[data-return-house]');if(home)return returnHouse(event);
  const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;
  if(action==='close-dialog')return closeDialog();if(action==='close-inspector')return closeInspector();if(action==='reload')return location.reload();
  if(action==='dashboard')return showDashboard();
  if(action==='visit-airport'){
    if(busy)return;
    const target=list(view?.airports).find(a=>a.id===button.dataset.airportId&&a.owned);if(!target)return;
    if(target.id===view.selectedAirportId)return enterAirport();
    dashboard.setBusy(true);
    try{const result=await runCommand({type:'select-airport',airportId:target.id});if(result)enterAirport()}
    finally{dashboard.setBusy(false)}
    return;
  }
  if(['buildings','fleet','ground-fleet','research','network','milestones','boost','withdraw','help'].includes(action)&&!button.dataset.researchId)return openDialog(action);
  if(action==='equipment-angle'){equipmentRear=button.dataset.rear==='true';return renderDialog()}
  if(action==='fleet-filter'){fleetFilter=button.dataset.filter;return renderDialog()}
  if(action==='boost-multiplier'){boostMultiplier=number(button.dataset.multiplier);return renderDialog()}
  if(action==='withdraw-max'){const amount=$('#withdrawAmount');amount.value=Math.floor(airport().cash/10)*10;return updateWithdrawPreview()}
  if(busy){toast('Saving your last action. Try again in a moment.');return}const a=airport(),base={type:action,airportId:button.dataset.airportId||a?.id};
  if(button.dataset.useDiamonds)base.useDiamonds=true;
  if(action==='upgrade'){base.building=button.dataset.building;return runCommand(base,'Your upgrade has started. The airport stays open.')}
  if(action==='build-gate'){base.plotId=button.dataset.plotId;base.size=number(button.dataset.size);return runCommand(base,'A new gate is on its way.')}
  if(action==='set-gate-active'){base.gateId=button.dataset.gateId;base.active=button.dataset.active==='true';return runCommand(base,'Bay operating space updated.')}
  if(action==='upgrade-gate'){base.gateId=button.dataset.gateId;return runCommand(base,'Gate expansion is underway.')}
  if(action==='research'){base.researchId=button.dataset.researchId;return runCommand(base,'Research has started.')}
  if(action==='skip-task'){base.taskId=button.dataset.taskId;return runCommand(base,'Your project is complete.')}
  if(action==='activate-boost'){base.type='boost';base.multiplier=boostMultiplier;base.durationMinutes=boostDuration;return runCommand(base,`${boostMultiplier}× boost is active at ${a.name}.`)}
  if(action==='claim-milestone'){base.milestoneId=button.dataset.milestoneId;return runCommand(base,'Milestone reward collected. Nice flying!')}
  if(action==='unlock-airport'){const result=await runCommand(base,'Your next airport is open for business.');if(result){closeDialog();closeInspector()}return}
  if(action==='select-airport'){const result=await runCommand(base);if(result){closeDialog();closeInspector()}return}
}
function trapFocus(event){
  if(event.key==='Escape'){if(dialog)closeDialog();else closeInspector();return}
  if(event.key!=='Tab'||!dialog)return;const elements=[...$('.dialog-card').querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),[tabindex="0"]')].filter(el=>el.offsetParent!==null);const first=elements[0],last=elements.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===$('.dialog-card'))){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}
}
function fatal(error){disposed=true;clearInterval(pollTimer);clearInterval(clockTimer);renderer?.dispose();$('#airportLoading').hidden=true;$('#airportHud').hidden=true;$('#airportDashboard').hidden=true;$('#airportFatal').hidden=false;$('#airportApp').setAttribute('aria-busy','false');const message=error?.message||'Your cloud airport could not be loaded.';$('#airportFatalCopy').textContent=['SESSION_REPLACED','AUTH_REQUIRED','UNAUTHORIZED','SESSION_EXPIRED','AUTH_SESSION_ENDED','ACCOUNT_DISABLED'].includes(error?.code)?`${message} Return to Dorra House to sign in and resume your saved airports.`:`${message} Check your internet connection, then try again. Your last cloud save is preserved.`}
async function initialize(){
  document.addEventListener('click',event=>{handleClick(event).catch(error=>toast(error.message,true))});
  document.addEventListener('keydown',trapFocus);
  document.addEventListener('change',event=>{if(event.target.id==='boostDuration'){boostDuration=number(event.target.value);renderDialog()}else if(event.target.dataset.plotSize){plotSizes.set(`${airport().id}:${event.target.dataset.plotSize}`,number(event.target.value));if(dialog)renderDialog();if(inspector)renderInspector()}});
  document.addEventListener('input',event=>{if(event.target.id==='withdrawAmount')updateWithdrawPreview()});
  document.addEventListener('submit',event=>{if(event.target.id==='withdrawForm')withdraw(event)});
  vault=await createVaultClient({onStatus:saveStatus});
  if(typeof vault.airportLoad!=='function')throw new Error('The airport cloud service could not be loaded. Reload Dorra House to reconnect.');
  const result=await vault.airportLoad();applyResult(result);initialIdle=result;
  $('#airportLoading').hidden=true;$('#airportApp').setAttribute('aria-busy','false');showDashboard();saveStatus('saved');
  if(number(result.elapsedMs)>=300_000)openDialog('idle');
  pollTimer=setInterval(poll,POLL_INTERVAL_MS);clockTimer=setInterval(updateClocks,1000);warmFleetArt();
  document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!disposed)poll()});
  window.addEventListener('pagehide',()=>{disposed=true;clearInterval(pollTimer);clearInterval(clockTimer);renderer?.dispose();vault?.close()},{once:true});
}
initialize().catch(fatal);
